fvar Q=Q.COLLADA,O={up_axis:1,images:[],effects:[],materials:[],meshes:[],scenes:[],lights:[],cameras:[],animations:[]};if(Q.asset){var La=Q.asset.up_axis.$;"X_UP"===La?O.up_axis=0:"Y_UP"===La?O.up_axis=1:"Z_UP"===La&&(O.up_axis=2)}var gb=O.up_axis;if(Q.library_images&&(Q.library_images.image&&!Q.library_images.image.length&&(Q.library_images.image=[Q.library_images.image]),Q.library_images.image.length))for(var hb=Q.library_images.image,Ma=0,pb=hb.length;Ma<pb;Ma++){var Na=hb[Ma],ib=Na["@id"],Gc=
Na["@name"],Zb=Na.init_from;if(Zb.$){var ra=Zb.$;a!==w&&-1!==ra.lastIndexOf("/")&&(ra=ra.substr(ra.lastIndexOf("/")+1));a!==w&&-1!==ra.lastIndexOf("\\")&&(ra=ra.substr(ra.lastIndexOf("\\")+1));O.images[ib]={source:ra,id:ib,name:Gc}}}var jb,qb,$b,W,Oa,ka,Pa,da,P,X,T,Da,ga,Qa,Ra,Z,aa;if(Q.library_effects){var Sa=Q.library_effects.effect;Sa&&!Sa.length&&(Sa=[Sa]);qb=0;for($b=Sa.length;qb<$b;qb++){var Cb=Sa[qb];jb=Cb["@id"];var U={};U.id=jb;U.surfaces=[];U.samplers=[];(da=Cb.profile_COMMON.newparam)&&
!da.length&&(da=[da]);if(da){S=0;for(ca=da.length;S<ca;S++){var sa=da[S],Ta=sa["@sid"];if(sa.surface){U.surfaces[Ta]={};var ac=sa.surface.init_from.$;"object"===typeof O.images[ac]&&(U.surfaces[Ta].source=a+"/"+O.images[ac].source)}else if(sa.sampler2D&&(U.samplers[Ta]={},U.samplers[Ta].source=sa.sampler2D.source.$,sa.sampler2D.minfilter&&(U.samplers[Ta].minfilter=sa.sampler2D.minfilter.$),sa.sampler2D.magfilter))U.samplers[Ta].magfiter=sa.sampler2D.magfilter.$}}var va=Cb.profile_COMMON.technique;
va&&!va.length&&(va=[va]);U.material={textures_ref:[]};W=0;for(Oa=va.length;W<Oa;W++){g=va[W].blinn;g||(g=va[W].phong);g||(g=va[W].lambert);if(g)for(var ea in g){var rb=g[ea],ta=c(rb),bc=d(rb),cc=!rb.texture?!1:rb.texture["@texture"];!1!==ta&&3<ta.length&&ta.pop();"emission"==ea?!1!==ta&&(U.material.ambient=ta):"ambient"!=ea&&("diffuse"==ea?!1!==ta&&(U.material.color=ta):"specular"==ea?!1!==ta&&(U.material.specular=ta):"shininess"==ea&&!1!==bc&&(U.material.shininess=bc));if(!1!==cc){var Ua=U.surfaces[U.samplers[cc].source].source;
"emission"==ea?U.material.textures_ref.push({image:Ua,type:q.texture.map.AMBIENT}):"ambient"==ea?U.material.textures_ref.push({image:Ua,type:q.texture.map.AMBIENT}):"diffuse"==ea?U.material.textures_ref.push({image:Ua,type:q.texture.map.COLOR}):"specular"==ea?U.material.textures_ref.push({image:Ua,type:q.texture.map.SPECULAR}):"shininess"!=ea&&("reflective"==ea?U.material.textures_ref.push({image:Ua,type:q.texture.map.REFLECT}):"reflectivity"!=ea&&"transparent"==ea&&U.material.textures_ref.push({image:Ua,
type:q.texture.map.ALPHA}))}}O.effects[jb]=U}}}var Db=b.getAllOf(Q,"instance_geometry"),sb=[];if(Db.length){u=0;for(E=Db.length;u<E;u++){var dc=Db[u],Eb=b.getAllOf(dc,"instance_material");if(Eb.length){V=0;for(na=Eb.length;V<na;V++){var ec=Eb[V],Hc=ec["@symbol"],Ic=ec["@target"].substr(1);sb[dc["@url"].substr(1)+":"+Hc]=Ic}}}}var Fb=Q.library_materials;if(Fb&&Fb.material){var Va=Fb.material;Va&&!Va.length&&(Va=[Va]);F=0;for(H=Va.length;F<H;F++){var Gb=Va[F],Jc=Gb["@id"],Kc=Gb["@name"],fc=Gb.instance_effect;
fc&&(jb=fc["@url"].substr(1),O.materials.push({id:Jc,name:Kc,mat:O.effects[jb].material}))}}var gc=Q.library_geometries,Wa;if(gc){var ua=gc.geometry;ua&&!ua.length&&(ua=[ua]);if(ua.length)for(var kb=0,Lc=ua.length;kb<Lc;kb++){var ma={id:w,points:[],parts:[]},Xa=ua[kb].mesh;if(Xa){Wa=ua[kb]["@id"];n=ua[kb]["@name"];var Ya=Xa.source;Ya&&!Ya.length&&(Ya=[Ya]);for(var R=[],Hb=0,Mc=Ya.length;Hb<Mc;Hb++){var tb=Ya[Hb];o=tb["@id"];var Nc=tb["@name"],Ib=tb.float_array;Ib&&(R[o]={id:o,name:Nc,data:e.floatDelimArray(Ib.$?
Ib.$:""," ")});var Jb=tb.technique_common.accessor;Jb&&(R[o].count=Jb["@count"]|0,R[o].stride=Jb["@stride"]|0,R[o].count&&(R[o].data=e.repackArray(R[o].data,R[o].stride,R[o].count)))}var Kb=Xa.vertices,lb=null,Lb=null,Ea=null,Fa=null,Ga=null;if(Kb&&(Lb=Kb["@id"],(P=Kb.input)&&!P.length&&(P=[P]),P)){ka=0;for(Pa=P.length;ka<Pa;ka++)X=P[ka],"POSITION"===X["@semantic"]&&(lb=X["@source"].substr(1))}var oa=Xa.triangles;oa&&!oa.length&&(oa=[oa]);if(oa){W=0;for(Oa=oa.length;W<Oa;W++){aa={material:0,faces:[],
normals:[],texcoords:[],colors:[]};var Oc=parseInt(oa[W]["@count"],10);(P=oa[W].input)&&!P.length&&(P=[P]);T=[];if(P.length){ka=0;for(Pa=P.length;ka<Pa;ka++)X=P[ka],Z=parseInt(X["@offset"],10),r=X["@source"].substr(1),"VERTEX"===X["@semantic"]?(r===Lb&&(r=lb),T[Z]=0):"NORMAL"===X["@semantic"]?(Ea=r,R[Ea].count&&(T[Z]=1)):"TEXCOORD"===X["@semantic"]?(Ga=r,R[Ga].count&&(T[Z]=2)):"COLOR"===X["@semantic"]?(Fa=r,R[Fa].count&&(T[Z]=3)):T[Z]=4}C=T.length;m=Wa+":"+oa[W]["@material"];null===m?aa.material=
0:sb[m]===w?(s("missing material ["+m+"]@"+Wa+"?"),aa.material=0):aa.material=sb[m];var hc=oa[W].p,wa=[];hc&&(wa=e.intDelimArray(hc.$," "));if(wa.length&&(y=wa.length/T.length/3,y===Oc)){0===ma.points.length&&(ma.points=R[lb].data);u=Z=0;E=wa.length;for(z=T.length;u<E;u+=3*z){t=[];A=[];D=[];ha=[];for(V=0;V<3*z;V++){var ub=V%z;0===T[ub]?A.push(wa[u+V]):1===T[ub]?t.push(wa[u+V]):2===T[ub]?D.push(wa[u+V]):3===T[ub]&&ha.push(wa[u+V])}A.length&&(aa.faces.push(A),3===t.length&&aa.normals.push([b.fixuaxis(O.up_axis,
R[Ea].data[t[0]]),b.fixuaxis(O.up_axis,R[Ea].data[t[1]]),b.fixuaxis(O.up_axis,R[Ea].data[t[2]])]),3===D.length&&aa.texcoords.push([R[Ga].data[D[0]],R[Ga].data[D[1]],R[Ga].data[D[2]]]),3===ha.length&&aa.colors.push([R[Fa].data[ha[0]],R[Fa].data[ha[1]],R[Fa].data[ha[2]]]))}}ma.parts.push(aa)}}var ia=Xa.polylist;ia||(ia=Xa.polygons);ia&&!ia.length&&(ia=[ia]);if(ia){W=0;for(Oa=ia.length;W<Oa;W++){aa={material:0,faces:[],normals:[],texcoords:[],colors:[]};var ic=parseInt(ia[W]["@count"],10);(P=ia[W].input)&&
!P.length&&(P=[P]);T=[];if(P.length){ka=0;for(Pa=P.length;ka<Pa;ka++){X=P[ka];var Mb=X["@offset"];null===Mb&&(Mb=X["@idx"]);Z=parseInt(Mb,10);r=X["@source"].substr(1);"VERTEX"===X["@semantic"]?(r===Lb&&(r=lb),T[Z]=0):"NORMAL"===X["@semantic"]?(Ea=r,T[Z]=1):"TEXCOORD"===X["@semantic"]?(Ga=r,T[Z]=2):"COLOR"===X["@semantic"]?(Fa=r,T[Z]=3):T[Z]=4}}var jc=ia[W].vcount,Za=[];jc&&(Za=e.intDelimArray(jc.$," "));m=Wa+":"+ia[W]["@material"];aa.material=m===w?0:sb[m];var mb=ia[W].p;C=T.length;var xa=[];if(1<
mb.length&&!Za.length){S=0;for(ca=mb.length;S<ca;S++){var kc=e.intDelimArray(mb[S].$," ");Za[S]=parseInt(kc.length/C,10);xa=xa.concat(kc)}}else mb&&(xa=e.intDelimArray(mb.$," "));if(xa.length)if(y=Za.length,y!==ic)s("poly vcount data doesn't add up, skipping object load: "+y+" !== "+ic);else{0===ma.points.length&&(ma.points=R[lb].data);u=Z=0;for(E=Za.length;u<E;u++){t=[];A=[];D=[];ha=[];V=0;for(na=Za[u]*C;V<na;V++)0===T[V%C]?A.push(xa[Z]):1===T[V%C]?t.push(xa[Z]):2===T[V%C]?D.push(xa[Z]):3===T[V%
C]&&ha.push(xa[Z]),Z++;var $a;if(A.length){aa.faces.push(A);if(t.length){$=[];G=0;for(J=t.length;G<J;G++)$.push(b.fixuaxis(O.up_axis,R[Ea].data[t[G]]));aa.normals.push($)}if(D.length){$a=[];G=0;for(J=D.length;G<J;G++)$a.push(R[Ga].data[D[G]]);aa.texcoords.push($a)}if(ha.length){$a=[];G=0;for(J=ha.length;G<J;G++)$a.push(R[Fa].data[ha[G]]);aa.colors.push($a)}}}}ma.parts.push(aa)}}if(1!==gb){u=0;for(E=ma.points.length;u<E;u++)ma.points[u]=b.fixuaxis(O.up_axis,ma.points[u])}ma.id=Wa;O.meshes.push(ma)}}}var lc=
Q.library_cameras;if(lc){(Qa=lc.camera)&&!Qa.length&&(Qa=[Qa]);L=0;for(M=Qa.length;L<M;L++){ga=Qa[L];var Pc=ga["@id"],vb=0,wb=0,xb=0;ga.optics&&(ga.optics.technique_common&&ga.optics.technique_common.perspective)&&(vb=ga.optics.technique_common.perspective.yfov,wb=ga.optics.technique_common.perspective.znear,xb=ga.optics.technique_common.perspective.zfar);var Nb,Ob,Pb;if(!vb&&!wb&&!xb){(da=ga.param)&&!da.length&&(da=[da]);u=0;for(E=da.length;u<E;u++){var Qb=da[u].$,Rb=da[u]["@name"];"YFOV"==Rb?Nb=
parseFloat(Qb):"ZNEAR"==Rb?Ob=parseFloat(Qb):"ZFAR"==Rb&&(Pb=parseFloat(Qb))}}else Nb=vb?parseFloat(vb.$):60,Ob=wb?parseFloat(wb.$):0.1,Pb=xb?parseFloat(xb.$):1E3;O.cameras.push({id:Pc,targeted:!1,fov:parseFloat(Nb),nearclip:parseFloat(Ob),farclip:parseFloat(Pb)})}}var mc=Q.library_lights,ab;if(mc){var Ha=mc.light;Ha&&!Ha.length&&(Ha=[Ha]);if(Ha)for(var Sb=0,Qc=Ha.length;Sb<Qc;Sb++){ab=Ha[Sb];var nc=ab.technique_common.point,yb=nc?nc:null,oc=ab["@id"];if(null!==yb){var pc=yb.intensity,Rc=pc?parseFloat(pc.$):
1,qc=yb.distance,Sc=qc?parseFloat(qc.$):10,rc=yb.color,ha=[1,1,1];rc&&(ha=e.floatDelimArray(rc.$," "));O.lights.push({id:oc,name:oc,type:q.light.type.POINT,method:q.light.method.STATIC,diffuse:ha,specular:[0,0,0],distance:Sc,intensity:Rc})}}}var sc=Q.library_visual_scenes;if(sc){var bb=null;(bb=sc.visual_scene)&&!bb.length&&(bb=[bb]);for(var Tb=0,Tc=bb.length;Tb<Tc;Tb++){Ra=bb[Tb];var ya={id:Ra["@id"],sceneObjects:[],cameras:[],lights:[],parentMap:[]},pa=[],cb=[],za,Ub,la,ba,$,tc=Q.library_nodes;
if(tc){var db=tc.node;db&&!db.length&&(db=[db]);pa=[];u=0;for(E=db.length;u<E;u++)Ub=db[u],mnodeId=Ub["@id"],pa[la]=Ub;for(za=[Ra];za.length;){ba=za.pop();if(ba.node&&(($=ba.node)&&!$.length&&($=[$]),$)){u=0;for(E=$.length;u<E;u++)za.push($[u])}if(ba.instance_node){var eb=ba.instance_node;eb&&!eb.length&&(eb=[eb]);u=0;for(E=eb.length;u<E;u++){var Vb=eb[u]["@url"].substr(1);pa[Vb]&&(ba.node&&ba.node.length&&(ba.node=[ba.node]),ba.node?ba.node.push(pa[Vb]):ba.node=[pa[Vb]])}}}}for(za=[Ra];za.length;)if(ba=
za.pop(),ba.node&&(($=ba.node)&&!$.length&&($=[$]),$)){u=0;for(E=$.length;u<E;u++)$[u].parentNode=ba,cb.push($[u]),za.push($[u])}if(cb.length)for(var nb=0,Uc=cb.length;nb<Uc;nb++){var Aa=cb[nb],Ba=Aa.instance_geometry;ab=cb[nb].instance_light;ga=cb[nb].instance_camera;la=Aa["@id"];var fa=Aa["@name"],ja=b.cl_getInitalTransform(O.up_axis,Aa);2===gb&&(ja.rotation=b.quaternionFilterZYYZ(ja.rotation,ga?[-90,0,0]:w));var ob=null,Y=null,fb;if(Ba){Ba&&!Ba.length&&(Ba=[Ba]);u=0;for(E=Ba.length;u<E;u++)if(n=
Ba[u]["@url"].substr(1),Y={},Y.name=(fa?fa:la)+(u?u:""),Y.id=(la?la:fa)+(u?u:""),Y.meshId=Wa,Y.meshName=n,ob||(Y.position=ja.position,Y.rotation=ja.rotation,Y.scale=ja.scale,Y.matrix=ja.matrix),ya.sceneObjects.push(Y),pa[Y.id]=!0,Aa.parentNode)(fb=Aa.parentNode["@id"])&&pa[fb]?ya.parentMap.push({parent:fb,child:Y.id}):1<Ba.length&&(ob?pa[ob.id]&&ya.parentMap.push({parent:ob.id,child:Y.id}):(ob=Y,Y={}))}else if(ga){var Vc=ga["@url"].substr(1);ya.cameras.push({name:fa?fa:la,id:fa?fa:la,source:Vc,position:ja.position,
rotation:ja.rotation})}else if(ab){var Wc=ab["@url"].substr(1);ya.lights.push({name:fa?fa:la,id:fa?fa:la,source:Wc,position:ja.position})}else Y={position:ja.position,rotation:ja.rotation,scale:ja.scale,matrix:ja.matrix},Y.name=fa?fa:la,Y.id=la?la:fa,ya.sceneObjects.push(Y),pa[Y.id]=!0,Aa.parentNode&&(fb=Aa.parentNode["@id"])&&pa[fb]&&ya.parentMap.push({parent:fb,child:Y.id})}O.scenes.push(ya)}}var uc=Q.library_animations,qa;if(uc){var Ia=uc.animation;Ia&&!Ia.length&&(Ia=[Ia]);if(Ia)for(var Wb=0,
Xc=Ia.length;Wb<Xc;Wb++){var zb=Ia[Wb];qa=zb["@id"];O.animations[qa]={};O.animations[qa].sources=[];var Ja=zb.source;Ja&&!Ja.length&&(Ja=[Ja]);if(Ja.length){K=0;for(N=Ja.length;K<N;K++){var Ca=Ja[K];o=Ca["@id"];var vc=Ca.technique_common,Ab=null,wc=null;Ca.name_array?Ab=e.textDelimArray(Ca.name_array.$," "):Ca.Name_array?Ab=e.textDelimArray(Ca.Name_array.$," "):Ca.float_array&&(wc=e.floatDelimArray(Ca.float_array.$," "));var Xb=0,xc="",Bb=1;if(vc){g=vc;var Yb=g.accessor,Xb=parseInt(Yb["@count"],10),
xc=Yb["@source"].substr(1),yc=Yb["@stride"];yc&&(Bb=parseInt(yc,10))}O.animations[qa].sources[o]={data:Ab?Ab:wc,count:Xb,source:xc,stride:Bb};1!==Bb&&(O.animations[qa].sources[o].data=e.repackArray(O.animations[qa].sources[o].data,Bb,Xb))}}(Da=zb.sampler)&&!Da.length&&(Da=[Da]);if(Da){O.animations[qa].samplers=[];K=0;for(N=Da.length;K<N;K++){var zc=Da[K],Yc=zc["@id"];(P=zc.input)&&!P.length&&(P=[P]);if(P){var Ac=[];x=0;for(E=P.length;x<E;x++)X=P[x],Ac[X["@semantic"]]=X["@source"].substr(1);O.animations[qa].samplers[Yc]=
Ac}}}var Ka=zb.channel;Ka&&!Ka.length&&(Ka=[Ka]);if(Ka){O.animations[qa].channels=[];L=0;for(M=Ka.length;L<M;L++){var Bc=Ka[L],Zc=Bc["@source"].substr(1),Cc=Bc["@target"],Dc=Cc.split("/"),$c=Dc[0],Ec=Dc[1].split(".");O.animations[qa].channels.push({source:Zc,target:Cc,targetName:$c,paramName:Ec[0],typeName:Ec[1]})}}}}var Fc=Q.scene;if(Fc&&(Ra=Fc.instance_visual_scene)){var ad=Ra["@url"].substr(1);O.scene=ad}return O}var w=h.undef,q=h.enums,n=h.GLCore,s=h.log,b={fixuaxis:function(b,a){if(0===b)return[a[1],
