function() {
            // Load all the materials
            this.addMaterial(new FlatMaterial());
            this.addMaterial(new BumpMetalMaterial());
            //this.addMaterial(new CloudMaterial());
            //this.addMaterial(new DeformMaterial());
            this.addMaterial(new FlagMaterial());
            //this.addMaterial(new FlyMaterial());
            //this.addMaterial(new JuliaMaterial());
            //this.addMaterial(new KeleidoscopeMaterial());
            this.addMaterial(new LinearGradientMaterial());
            //this.addMaterial(new MandelMaterial());
            this.addMaterial(new ParisMaterial());
            this.addMaterial(new PlasmaMaterial());
            this.addMaterial(new PulseMaterial());
            //this.addMaterial(new RadialBlurMaterial());
            this.addMaterial(new RadialGradientMaterial());
            //this.addMaterial(new RaidersMaterial());
            //this.addMaterial(new ReliefTunnelMaterial());
            //this.addMaterial(new SquareTunnelMaterial());
            //this.addMaterial(new StarMaterial());
            this.addMaterial(new TaperMaterial());
            //this.addMaterial(new TunnelMaterial());
            //this.addMaterial(new TwistMaterial());
            this.addMaterial(new TwistVertMaterial());
            this.addMaterial(new UberMaterial());
            this.addMaterial(new WaterMaterial());
            //this.addMaterial(new ZInvertMaterial());
        }