function anonymous(locals, attrs, escape, rethrow) {
  var attrs = jade.attrs, escape = jade.escape, rethrow = jade.rethrow;
  var buf = [];
  with (locals || {}) {
  var interp;
  buf.push('<div');
  buf.push(attrs({ 'id':('main'), "class": ('table-ly-wrpr') }));
  buf.push('><!-- boutons for the editor--><div');
  buf.push(attrs({ 'id':('divMainBtn'), "class": ('table-ly-hder') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('generalBtnBar'), "class": ('btn-group') }));
  buf.push('><button');
  buf.push(attrs({ 'id':('EmptyTextBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Init texte vide  </button><button');
  buf.push(attrs({ 'id':('SimpleTextBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Init texte simple</button><button');
  buf.push(attrs({ 'id':('FullTextBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Init texte long</button><button');
  buf.push(attrs({ 'id':('logKeysBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Log keystrokes</button><button');
  buf.push(attrs({ 'id':('logRangeBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Log range</button><button');
  buf.push(attrs({ 'id':('printRangeBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Print Range</button><button');
  buf.push(attrs({ 'id':('addClass2LineBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Add Class on Lines</button></div><select');
  buf.push(attrs({ 'id':('contentSelect') }));
  buf.push('><option');
  buf.push(attrs({ 'value':("content-full"), 'style':("display:block") }));
  buf.push('>Full note</option><option');
  buf.push(attrs({ 'value':("content-full-marker"), 'style':("display:block") }));
  buf.push('>Tout en puces</option><option');
  buf.push(attrs({ 'value':("content-shortlines-marker"), 'style':("display:block") }));
  buf.push('>Tout en puce, lignes courtes</option><option');
  buf.push(attrs({ 'value':("content-shortlines-all"), 'style':("display:block") }));
  buf.push('>Puces et titres, lignes courtes</option><option');
  buf.push(attrs({ 'value':("content-empty"), 'style':("display:block") }));
  buf.push('>Empty note</option><option');
  buf.push(attrs({ 'value':("content-full-relative-indent"), 'style':("display:block") }));
  buf.push('>Avec sommaire</option></select><select');
  buf.push(attrs({ 'id':('cssSelect') }));
  buf.push('><option');
  buf.push(attrs({ 'value':("images/editor2.css"), 'style':("display:block") }));
  buf.push('>css1</option><option');
  buf.push(attrs({ 'value':("stylesheets/app.css"), 'style':("display:block") }));
  buf.push('>css2</option></select></div><div');
  buf.push(attrs({ 'id':('main-div'), "class": ('table-ly-ctnt') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('col-wrap') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('editor-col') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('well-editor'), "class": ('monWell') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('editorDiv'), "class": ('table-ly-wrpr') }));
  buf.push('><!-- boutons for the editor--><div');
  buf.push(attrs({ "class": ('table-ly-hder') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('editorBtnBar'), "class": ('btn-group') }));
  buf.push('><button');
  buf.push(attrs({ 'id':('indentBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Indent</button><button');
  buf.push(attrs({ 'id':('unIndentBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Un-indent</button><button');
  buf.push(attrs({ 'id':('markerListBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>- Marker list</button><button');
  buf.push(attrs({ 'id':('titleBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>1.1.2 Title</button><button');
  buf.push(attrs({ 'id':('checkBtn'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Checking OFF</button><button');
  buf.push(attrs({ 'id':('CozyMarkdown'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Markdown</button></div></div><!-- text for the editor--><div');
  buf.push(attrs({ 'id':('editorContent'), "class": ('table-ly-ctnt') }));
  buf.push('><iframe');
  buf.push(attrs({ 'id':('editorIframe') }));
  buf.push('></iframe></div></div></div></div><div');
  buf.push(attrs({ 'id':('result-col') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('well-result'), "class": ('monWell') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('resultDiv'), "class": ('table-ly-wrpr') }));
  buf.push('><div');
  buf.push(attrs({ "class": ('table-ly-hder') }));
  buf.push('><div');
  buf.push(attrs({ 'id':('resultBtnBar'), "class": ('btn-group') }));
  buf.push('><button');
  buf.push(attrs({ 'id':('resultBtnBar_coller'), "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>Coller</button><button');
  buf.push(attrs({ "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>-</button><button');
  buf.push(attrs({ "class": ('btn') + ' ' + ('btn-small') + ' ' + ('btn-primary') }));
  buf.push('>-</button></div><p');
  buf.push(attrs({ 'id':('editorPropertiesDisplay') }));
  buf.push('></p></div><!-- text for the resulting html--><div');
  buf.push(attrs({ 'id':('resultContent'), "class": ('table-ly-ctnt') }));
  buf.push('><textarea');
  buf.push(attrs({ 'id':('resultText') }));
  buf.push('></textarea></div></div></div></div></div></div></div>');
  }
  return buf.join("");
  }