function(){
		var loc = CORP.request['location'];

		popcorn = new Popcorn('#video', {
			frameAnimation: true
		});

		popcorn.defaults('influenceExplorer', {
			apikey: sunlightAPIKey,
			target: 'video-container'
		});

		popcorn.defaults('stateExplorer', {
			apikey: sunlightAPIKey,
			target: 'video-container',
			state: loc && loc.country_code === 'US' && loc.region_code
		});

		popcorn.defaults('stateInfo', {
			target: 'video-container',
			state: loc && loc.country_code === 'US' && loc.region_code
		});

		popcorn.influenceExplorer({
			start: 2,
			end: 6,
			orgId: '86656f0dca46422e997aade92cfd0419',
			orgName: 'Americans for Prosperity',
			pacHtml: 'Americans for Prosperity was founded by billionaire brothers David and Charles Koch, owners of Koch Industries to back conservative issue like small government  and  lower taxes.  The group refuses to disclose how much it spends on outside electioneering activities in Wisconsin and elsewhere through its 501(c)(4) and its 501(c)(3) charitable arms.',
			html: 'Americans for Prosperity spent millions on television ads in Wisconsin in support of Gov. Walker in 2011-2012, according to local television ad buy reports reviewed by the Wisconsin Democracy Campaign. These expenditures are not required to be disclosed publicly.'
		});

		popcorn.influenceExplorer({
			start: 15,
			end: 21,
			orgId: '7416a2e232fa434e99b520d7603e09a9',
			orgName: 'Campaign to Defeat Barack Obama',
			pacHtml: 'The Campaign to Defeat Barack  Obama is a California-based organization formed to defeat President  Barack Obama in the 2012 presidential election.',
			html: 'The Campaign to Defeat Barack Obama  has not registered to make independent expenditures in Wisconsin elections, even though it sponsored broadcast advertising in the 2011 and 2012 recall elections.The group is closely affiliated with prominent national Tea Party activists. Joe Wierzbicki, one of the group\'s leaders explains the group\'s interest in Wisconsin: "The reason we\'ve  been so focused on Wisconsin is that the ramifications of the recall election are huge. There are ten Electoral Votes at stake here in  Wisconsin, and this will likely be one of the most important swing  states come November." (<a href="http://prospect.org/article/campaign-defeat-barack-obama-focused-largely-wisconsin" target="_blank">The Campaign to Defeat Barack Obama, Focused Largely in Wisconsin</a>, The American Prospect, April 25, 2012)'
		});

		popcorn.influenceExplorer({
			start: 21,
			end: 24,
			orgName: 'Greater Wisconsin Political Fund',
			pacHtml: 'The Greater Wisconsin Political Fund is a independent political organization, known as a 527, which engages in activities that support public issues, public officials, and  candidates for public office. Sister organizations include the 501(c)(4) issue advocacy group Greater Wisconsin Committee, and a PAC, The Greater Wisconsin Political Action Committee. ',
			html: 'From <a href="http://www.wisdc.org/gwc12recall.php" target="_blank">Wisconsin Democracy Campaign:</a> "Like all phony issue ad  groups, Greater Wisconsin refuses to disclose much of its fundraising  and spending in detail, but it\'s support comes from organized labor and  Democratic ideological groups supported by wealthy business interests.   Greater Wisconsin operates four entities - a political action committee,  a corporate arm that makes independent expenditures, a phony issue ad  group and a 527 group called the Greater Wisconsin Political Fund.." <a href="http://www.wisdc.org/gwc12recall.php" target="_blank">Read More</a>'
		});


		popcorn.influenceExplorer({
			start: '4:01',
			end: '4:17',
			orgId: '86656f0dca46422e997aade92cfd0419',
			orgName: 'Americans for Prosperity',
			pacHtml: 'Americans for Prosperity was founded by billionaire brothers David and Charles Koch, owners of Koch Industries to back conservative issue like small government  and  lower taxes.  The group refuses to disclose how much it spends on outside electioneering activities in Wisconsin and elsewhere through its 501(c)(4) and its 501(c)(3) charitable arms.',
			html: 'Americans for Prosperity spent millions on television ads in Wisconsin in support of Gov. Walker in 2011-2012, according to local television ad buy reports reviewed by the Wisconsin Democracy Campaign. These expenditures are not required to be disclosed publicly.'
		});

		popcorn.influenceExplorer({
			start: '4:43',
			end: '5:09',
			orgName: 'Greater Wisconsin Political Fund',
			pacHtml: 'The Greater Wisconsin Political Fund is a independent political organization, known as a 527, which engages in activities that support public issues, public officials, and  candidates for public office. Sister organizations include the 501(c)(4) issue advocacy group Greater Wisconsin Committee, and a PAC, The Greater Wisconsin Political Action Committee. ',
			html: 'From <a href="http://www.wisdc.org/gwc12recall.php" target="_blank">Wisconsin Democracy Campaign:</a> "Like all phony issue ad  groups, Greater Wisconsin refuses to disclose much of its fundraising  and spending in detail, but it\'s support comes from organized labor and  Democratic ideological groups supported by wealthy business interests.   Greater Wisconsin operates four entities - a political action committee,  a corporate arm that makes independent expenditures, a phony issue ad  group and a 527 group called the Greater Wisconsin Political Fund.." <a href="http://www.wisdc.org/gwc12recall.php" target="_blank">Read More</a>'
		});
		
		popcorn.influenceExplorer({
				start: '5:25',
			end: '5:32',
			orgId: 'a0951518abe24d7a95cb99dac25caf90',
			orgName: 'Restore Our Future, Inc.',
			pacHtml: 'ABOUT: Restore Our Future is a Super PAC that has raised more than $60 million to help secure the Republican nomination, and the Presidency, for Mitt Romney. <a href="http://reporting.sunlightfoundation.com/outside-spending/committee/restore-our-future-inc/C00490045/" target="_blank">Read More</a> ',
			html: 'Houston, Texas-based home builder Bob Perry has contributed $3,000,000.00 to Restore our Future, making him the largest single contributor.<p>Perry also contributed $500,000 to Gov. Scott Walker. What does he expect in return? <a href="http://videos-origin.mozilla.org/serv/webmademovies/silverhacks/citizencorp/tiaciara.webm" target="_blank">See what Scott Walker’s spokeswoman told us:</a>'
		});

		popcorn.influenceExplorer({
			start: '5:15',
			end: '5:20',
			orgId: '39738c686ce7438abc98587f651c102f',
			orgName: 'Progressive Change Campaign Cmte',
			html: 'This Democratic Political Action Committee spent $300,000 in Wisconsin in 2011-2012.'
		});

		popcorn.influenceExplorer({
			start: '5:24',
			end: '5:29',
			orgId: 'a0951518abe24d7a95cb99dac25caf90',
			orgName: 'Restore Our Future',
			html: ''
		});

		popcorn.stateInfo({
			start: '2:22.8',
			end: '2:52.3',
			title: 'Citizens United v. FEC Effect on States',
			html: '<p>"22 states had to look at their corporate prohibition laws and decide how to respond to the U.S. Supreme Court decision.  All but one, Montana, either repealed their independent expenditure prohibition laws or issued interpretations that declared the laws unenforceable...While most all the states repealed their corporate prohibitions on independent expenditures, in some instances... the attorneys general, the secretaries of state, or the enforcing commission issued rulings that the bans were no longer in effect. Most states just nullified their bans, but some states, including those that had not prohibited corporate independent expenditures, also passed legislation or regulations that enhanced the disclosure of independent expenditures."" --Corporate Reform Coalition report Sunlight State by State After Citizens United</p>' +
				'<p>State by state information excerpted from Corporate Reform Coalition*, June 2012 report: Sunlight State by State After Citizens United (*The Corporate Reform Coalition is more than 75 organizations and individuals from good governance groups, environmental groups and organized labor seeking to promote corporate governance solutions to combat undisclosed money in elections)</p>',
			AL: 'Score: 85. Alabama requires independent expenditures and a narrow form of electioneering communications to be reported within 120 days of an election if over $1,000. AL ST § 17-5-2. The reports are filed at the same time as committee reports, with weekly filings the last month before the election. Ads must say who is paying for them, with the name and address listed on the ad. AL ST § 17-5-2 (a) (4).',
			AK: 'Score: 100. Alaska gets the prize for the most innovative and far reaching laws adopted since Citizens United. In 2010, it passed urgency legislation, extended its independent disclosure provisions to corporations and made them even more transparent. Anyone making an independent expenditure must file reports. AS 15.13.040(e). Any late independent expenditure of over $250 made in the last nine days must be reported within 24 hours. AS 15.13.110(g). The law also applies to electioneering communications within the last 30 days before the election. AS 15.13.400(5). All communications must indicate who paid for them with the name and address of the source along with the name and title of the source’s principal officer. AS Sec. 15.13.090. It requires that the independent expenditure group list its top three donors in the ad by name and address. AS Sec. 15.13.090(a)(2)(C). In addition, the ad cannot make a defamatory statement about a candidate. AS 15.56 014 (a) (3).',
			AZ: 'Score: 70. Arizona enacted urgency legislation that changed its law to require corporations and labor organizations to file independent expenditure reports within 24 hours of making independent expenditures of $5,000 or more for statewide races and lesser amounts for other contests. Arizona Revised Statutes 16-914.02. There are no specific provisions on electioneering communications. All advertising must contain a statement listing the name of the organization in the ad. Arizona Revised Statutes 16-914.02(f) The disclosure does not have to be spoken on a TV ad as long as it lasts five seconds for a 30 second ad and ten seconds for a 60 second ad. The written disclosure must be at least four percent of the vertical picture height. The disclosure must say “Paid for by” and indicate that it was not authorized by any candidate or candidate’s campaign committee. Arizona Revised Statutes 16-914.02(f).',
			AR: 'Score: 40. Arkansas has not changed its laws or regulations since Citizens United. It started requiring disclosure of independent expenditures in 2009. Anyone who spends over $500 must file reports. Ark. Code Ann. Section 7-6-227 and Arkansas Ethics Commission Rules 700 et seq. There is no late independent expenditure reporting. Arkansas has no electioneering communication provision. Arkansas does not require an ad to indicate who paid for it within the ad itself.',
			CA: 'Score: 100. California requires disclosure of independent expenditures when they reach $1,000 or more. They must be itemized if $100 or more. CA GOVT Section 84203.5 (a). It requires late independent expenditures of $1,000 or more to filed within 24 hours if made within the last 17 days before the election. CA GOVT Section 84204 (a). Electioneering communication of $50,000 or more made within 45 days of the election must be disclosed within 48 hours of the communication along with the names of any person giving $5,000 or more to the entity making the communication. CA GOVT Section 85310. Ads paid for by independent expenditures must indicate who paid for them and the two highest contributors to the group paying for them if any contributions has given at least $50,000 or more. CA GOVT Section 84506. Any mass mailing of 200 pieces of more must prominently include the name and address of the entity responsible for the mailer if made by a committee (which also includes a corporation or individual who has made expenditures of $10,000 or more in a year.) CA GOVT CODE Section 84305.',
			CO: 'Score: 100. Colorado enacted urgency legislation in 2010 repealing its ban on corporate independent expenditures. The law stated that foreign corporations from out of the country could not make independent expenditures or contributions. The legislation established an elaborate disclosure system for independent expenditures of more than $1,000 in a calendar year. If money is given for an independent expenditure or an independent expenditure is made, then registration must be filed within two business days. Colorado Revised Statutes 1-45-107.5. Any person who contributes more than $250 to another person making an independent expenditure must be reported and any person giving $1,000 or more to another person making an independent expenditure must file according to the reporting schedules. Colorado Revised Statutes 1-45-107.5.(4)(b). Within 30 days of the election, disclosure reports must be filed within 48 hours. Otherwise the normal filing schedule is to be followed. CO CONST Art. 28, §5(1). Colorado requires electioneering communications of $1,000 or more made within 30 days of a primary election and 60 days before a general election to be reported at the same time as campaign reports. CO CONST Article XXVIII (2) (7). Any independent expenditure communication of over $1,000 that is broadcast or printed must indicate who paid for it and identify a natural person who is the registered agent for the entity. CO Revised Statutes 1-45-107.5 (5) (a).',
			CT: 'Score: 80. Connecticut repealed the ban on corporate independent expenditures and extended its disclosure provisions to them. If the independent expenditure is made more than 90 days before the election, it must be reported within 48 hours of the expenditure. CT ST Section 9-612(e). It changed its law to require reporting within 24 hours of the expenditure if made less than 90 days before the election (it had been 20 days before the election.) There is no electioneering communication provision. There also must be a disclaimer that the expenditure is independent of any candidate. In addition, at the end of the ad, there must appear at least a four second message from the chief executive of the entity saying “I am responsible for this ad” with proper identification of the person. CT ST Section 9-621(h). Any 527 organization must list its top five donors within the past 12 months in the ad except that in a radio ad of less than 30 seconds, the organization can refer the listener to a website with this information. These provisions apply to automated telephone calls as well as traditional ads. CT ST Section 9-621(h).',
			DE: 'Score: 80. Delaware has not changed its law since the early 1990s. It requires reporting of independent expenditures if over $100. DE ST TI 15 Section 8031 (a). Late independent expenditures of over $100 within 20 days of the election have to be reported within 24 hours. DE ST TI 15 Statue 8031 (b). The state has no electioneering communications section. Delaware requires that ads indicate who paid for them. DE ST TI 15 Statue 8021.',
			DC: 'Score: 90. Florida’s legislature passed a bill in 2010 that raised the independent expenditure threshold from $100 to $5,000. FL ST Section 106.071. There are no late independent expenditure reports although the last report is due four days before the election. FL ST Section 106.0703. Electioneering communications made within 30 days of a primary and 60 days before a general must be reported. FL ST Section 106.0703. Political ads must contain the following language: “Paid electioneering communication paid for by... (Name and address of person paying for the communication)....” FL ST Section 106.1439.',
			FL: 'Score: 50. Georgia has not changed its law since the Citizens United case. It requires that independent expenditures be reported. GA ST Section 21-5-34 (f) (1). Late independent expenditures of over $1,000 made within two weeks of the election must be reported within two business days. GA ST Section 21-5-34 (f) (1). There is no electioneering communication provision. Georgia has no ad disclosure provisions.',
			GA: 'Score: 100. Hawaii has not changed its disclosure laws for independent expenditures since the Citizens United decision. It does ban state contractor contributions to candidates, and that law has been challenged in court. HI ST Section 11-356. Yamada v. Kuromotoa, 744 F. Supp. 2d 1075 (2012) It requires reporting of independent expenditures of more than $1,000. HI ST Section 11-194 (d). Any late independent expenditures of over $1,000 made within 30 days of an election must be reported within two days. HI ST Section 11-194(d). Hawaii requires electioneering communications to be reported within 24 hours if over $2,000, made in the 30 days before a primary or 60 days before a general election and if the communication is susceptible to no other interpretation than an appeal to vote for or against a candidate. HI ST Section 11-341 All ads must contain the name and address of the person paying for them. HI ST Section 11-215(a).',
			HI: 'Score: 100. Idaho has had independent expenditure reporting since 1997. Independent expenditures of over $100 must be reported. ID ST 66-6611. Late independent expenditures of $1,000 or more within 15 days of the election must be reported within 48 hours. ID ST 66-6611(4). Idaho requires electioneering communications reporting for ads that unambiguously refer to a candidate appearing within 30 days of a primary and 60 days of a general election if over $100. ID ST 67-6630. It requires the name of the person sponsoring the ad to be listed in the ad. ID ST 67-6614(a).',
			ID: 'Score: 100. In 2010 Illinois required corporations and other entities to file independent expenditure reports if the entity spent over $3,000 for or against a candidate. Late independent expenditures of $1,000 or more made within 30 days before an election must be disclosed within five business days. ILCS 5 Election Code Sec. 9-10 (e). Electioneering communications that is susceptible to no reasonable interpretation other than as an appeal to vote for or against a clearly identified candidate for nomination for election, election, of over $3,000 made within 30 days of a primary and 60 days before a general election must be reported. ILCS 5 Election Code Sec. 9-1.14. Illinois requires a disclaimer on independent ads saying that the candidate did not authorize them as well as the name of the person paying for the ads. ILCS 5 Election Code Sec. 8 and 9-9.5.',
			IL: 'Score: 30. Indiana did not respond to Citizens United, partly because it had no ban on corporate independent expenditures. No significant campaign finance legislation has passed in years. Indiana does not require reporting of independent expenditure nor electioneering communications. Indiana requires a disclaimer on ads indicating that the candidate did not pay for them and identification of the person who paid for the ad. IN ST 3-9-3-2.5 (d).',
			IN: 'Score: 70. Iowa repealed its corporate independent expenditure ban and passed a law in 2010 that requires corporations to get the board of directors to approve any independent expenditures. IA ST Section 68A.404 2. (This provision has been challenged and upheld by a federal district judge; the decision is on appeal. The law also requires disclosure of independent expenditures of $750 or more within 48 hours of the expenditure. The disclosure has to indicate the candidate who has benefitted from the expenditure, but if the expenditure opposes a candidate, that candidate does not have to be reported. IA ST Section 68A.404 4. The independent expenditure entity may not hire an advertising firm that has been engaged or retained by the candidate, the candidate’s committee or the ballot measure committee that is benefiting from the independent expenditure. IA ST Section 68A.404 7. There is no electioneering communication provision. If the independent expenditure is made by a corporation, the words “paid for by” must be placed on the ad along with the name of the corporation and the name and title of the corporation’s chief executive officer. IA ST Section 68A.405 1.f. If a committee paid for the independent expenditure, only the name of the committee must appear on the ad. The published material must also specifically say that it was not authorized by any candidate or candidate committee. For television ads, the statement must appear on the screen for at least four seconds. IA ST Section 68A.405 3.',
			IA: 'Score: 70. Kansas has not done anything to respond since it always permitted corporate independent expenditures. It requires reporting of independent expenditures of $100 or more. KS ST § 25-4150. It does not require reporting of late independent expenditures. Electioneering communications are not reported.',
			KS: 'Score: 70. Kentucky’s ban on independent expenditures by corporations in its state constitution has been declared invalid by an opinion by the Kentucky Registry of Election Finance but not through legislation, so the constitutional provision is still on the books. The opinion noted that Kentucky’s disclosure provisions already in effect would apply to independent expenditures by corporations. These provisions require disclosure when independent expenditures of over $500 are made in any one election. KY ST Section 121.150 (1). There are no late independent expenditure provisions. There are no electioneering communications provisions. The name of the advertising sponsor must be put on any communication. KY ST § 121.190(1).',
			KY: 'Score: 50. Louisiana has not changed its laws or regulations since Citizens United. It requires reporting of independent expenditures of $500 or more. LA R.S. 18:1501.1 (A). Late independent expenditures of $1,000 or more made for statewide offices and $500 or more for legislative offices within 20 days of the election must be reported within 48 hours. LA R.S. 18:1501.1. It has no electioneering communications rules. Louisiana has no disclaimer and ad identification requirements.',
			LA: 'Score: 90. Maine has not enacted any more laws or regulations since Citizens United except for disclaimer provisions. It requires reporting of independent expenditures of more than $100. ME ST 21-A Section 1019-B. Late independent expenditures of over $250 must be reported within 24 hours. This was done by Commission rule. Maine Commission on Governmental Ethics and Campaign Practices. Rules: Section 10 of Chapter 1. Electioneering communications disclosure is required if a publicly financed candidate is mentioned in the last 21 days before a primary and 35 days before a general election. ME ST 21-A Section 1019-B. 1. B.\n\nIf an ad is not authorized by a candidate, there must be a disclaimer and disclosure of the name and address of the person who paid for the ad. ME ST 21-A Section 1014 2.',
			ME: 'Score: 90. Maryland passed a law that now requires reporting of independent expenditures of $10,000 or more in a four year election cycle. The law applies to corporations. MD Elec LawSection 13-306 (d ). It has no late independent expenditure reporting. It has an electioneering communications rule that requires disclosure of ads that reach at least 50,000 people and are made within the last 60 days before the election. MD Elec LawSection 13-307 (a) (3). Maryland requires a disclaimer on independent expenditure ads and disclosure of the name and address of the person responsible for it. MD Elec LawSection 13-401. Maryland requires disclosure of independent expenditures and electioneering communications to shareholders and members of political spending either on its website or if it has no website in a mailing to the shareholders. MD Elec Law Section 13-306 and 307.',
			MD: 'Score: 100. Massachusetts has not repealed its ban on corporate independent expenditures, but the Office of Campaign and Political Finance has issued a statement that it is no longer operative. It also requires anyone spending $250 or more on independent expenditures to file reports within seven business days. 55-18 A.(a). In addition, anyone making independent expenditures of $250 or more within 10 days of the election must file within 24 hours. MA ST 55-18 A.(b). Electioneering communications within 90 days must also be disclosed if $250 or more. MA ST 55-18 F. An ad on radio, television or internet paid for by an individual shall identify who is paying for the ad and their city or town. An ad paid for by a corporation or other group shall have a statement by the person in charge of the group (the chief executive of the corporation): his or her name, office, name of the corporation or group and the fact that the corporation or group paid for the ad. Statements on television have to show the person unobscured and with a full screen. MA ST 55-18 G.',
			MA: 'Score: 70. Michigan has not repealed its ban, but the Department of State has issued rulings saying the prohibition on corporate independent expenditures is invalid. Disclosure of independent expenditures was already required. If over $100, statements must be filed with the county within ten days. If over $500, registration must be filed with the state as well as the campaign statements. MI ST 169.251. If an independent expenditure is made within 45 days before a special election, a report of the expenditure shall be filed by the committee with the secretary of state within 48 hours after the expenditure. MI ST 169.233\n\nThere are no electioneering communication rules. An independent ad on television or radio must have a disclaimer that it was not authorized by the candidate and indicate who sponsored it as required by the Federal Communications Commission. Printed material must have the same disclaimer and identification. MI ST 169.247 (1-2).',
			MI: 'Score: 80. Minnesota’s ban on corporate independent expenditures was repealed by urgency legislation and the disclosure provisions apply to any corporate activity. Anyone making an independent expenditure of over $100 must file disclosure reports within 24 hours and must send a copy to the affected candidate. MN ST Section 10A.20 (Subd. 6b). There are no electioneering communications rules. All ads must indicate that they are an independent expenditure and must identify the source making the independent expenditure in conspicuous type on the front page of all literature and advertisements published or posted, and at the end of all broadcast advertisements. MN ST Section 10A.17. This law is on appeal en banc in the Eighth Circuit.',
			MN: 'Score: 40. Mississippi did not change its laws after the Citizens United decision. It requires disclosure of independent expenditures of over $200. MS ST Section 23-15-809. It does not have any late independent expenditure disclosure. It does not require any reporting of electioneering communications. It has no disclaimer or sponsor identification provisions on ads.',
			MO: 'Score: 65. Missouri has not passed any legislation or rules since Citizens United affecting corporations. Any independent expenditure of $500 or more must be reported. MO ST Section 130.047. A late independent expenditure made in the last 14 days shall be reported within 48 hours. MO ST Section 130.047. The state has no electioneering communications provisions. Missouri requires printed matter (but not TV or radio ads) to disclose who has paid for the ad. MO ST Section 130.031 (8). The Ethics Commission says in a handbook that federal laws must be followed for TV and radio ads.',
			MT: 'Score: 70. Montana is in court trying to uphold its ban on corporate independent expenditures dating back to 1912. It requires independent expenditures to be reported. MT ADC 44.10.531(4). Late independent expenditures are not required to be disclosed. There is no electioneering communication provision. An independent expenditure committee must send all candidates copies of ads printed or broadcast in the last 10 days before the election unless the ad was run previously. MT ST 13-35-402. An ad must conspicuously include the attribution “paid for” along with name and address of the person paying for it. If the material is printed and refers to a candidate’s voting record, the person financing the communication must be identified and sign a statement saying that the information is true to the best of the person’s knowledge. MT ST 13-35-225 (1, 3).',
			NE: 'Score: 80. Nebraska has had no legislation enacted since Citizens United was decided. It requires independent expenditures to be disclosed within 10 days if over $250. NE ST Section 49-1467 (1, 2). Late independent expenditures of $1,000 or more shall be reported within two days. NE ST Section 49-1478.01 (1, 3). Nebraska has no electioneering provisions. The name and address of the person paying for the ad shall be included in the ad. NE ST § 49-1474.01 (1-2).',
			NV: 'Score: 70. Nevada passed legislation in 2011. It requires reporting of independent expenditures over $100. NV ST Section 294A.210 (1). It has no late independent expenditure disclosure provisions. It has no electioneering communication provisions. It passed legislation in 2011 that requires any communication costing over $100 to list who is responsible for it. NV ST 294 A. 348.',
			NH: 'Score: 80. New Hampshire did not ban corporate independent expenditures although up until 2011, it had banned corporate contributions to candidates.\n\nAny independent expenditure over $500 must be reported within 24 hours if the entity making the independent expenditure is a political committee “major purpose is supporting or opposing a candidate. NH ST Section 664. Thus, it appears that a corporation making an independent expenditure would not have to file campaign statements since it would not qualify as a political committee. There is no electioneering communication provision. New Hampshire requires a disclaimer on ads not paid for by a candidate. The disclaimer must be: "This advertisement has been paid for by (name of sponsor) and has not been authorized by any candidate." In addition, the name and address of the sponsor must be listed on the ad. NH ST Section 664:14 (I, IV, VI, VII).',
			NJ: 'Score: 80. New Jersey has not changed any of its independent expenditure provisions in the last two years. It requires anyone making an independent expenditure of over $500 to file reports. N.J. Stat. Section 19:44A-11. Late independent expenditures over $500 made in the last 13 days must be reported. N.J. Stat. Section 19:44A-11. It has no electioneering communications laws. The name and address of the person paying for the ad must be included in the ad. NJ ST 19:44A-22.3 (a, e).',
			NM: 'Score: 40. New Mexico requires reporting of independent expenditures if over $500 in a calendar year. NM ST Section 1-19-26 (L). It has no late independent expenditure reporting. It has no electioneering communications provisions. It has no disclosure on ads because the Attorney General has issued an opinion saying that the provisions requiring the name of the sponsor be put on ads is unconstitutional. NM ST Section 1-19-16 and 11-19-17. AG’s Opinion 97-01.',
			NY: 'Score: 10. New York’s law has remained the same since the Citizens United decision although the Public Integrity Reform Act of 2011 requires the State Board of Elections to issue regulations specifying how independent expenditures and other expenditures that expressly identify a political candidate. The Board has proposed regulations, but they have not been adopted as of May, 2012. New York has a general section that can be interpreted to mean that the independent expenditures must be reported, but this section has yet not been enforced. NY ELEC Section 14-102 (1). It has no late independent expenditure provisions. It does not require electioneering communications to be reported although the Public Integrity Reform Act of 2011 could be interpreted by the Board of Elections to mandate such disclosures. Its proposed regulations, however, do not require such reports. New York has no disclosure on ads, but it does require copies of ads to be submitted after the election to the Board of Elections, which must retain them for a year. NY ELEC Section 14-106.',
			NC: 'Score: 100. North Carolina passed legislation in 2010 that removed the ban on corporate independent expenditures and clarified its reporting requirements for independent expenditures and electioneering communications. Independent expenditures of over $100 must be reported within 30 days or by 10 days before the election. NC GS Section 163-278.12 (d). An independent expenditure of $5,000 or more must be reported within 48 hours as must contributions to independent expenditure committees of $1,000 or more if made after the last filing deadline. NC GS Section 163-278.12 (e) Electioneering communications within 60 days must be reported. NC GS Section 163-278.12C. In a print advertisement that is an independent expenditure or an electioneering communication, the sponsor must disclose the names of the individuals or persons making the five largest donations to the sponsor within the six-month period prior to the purchase of the advertisement. A television or radio advertisement purchased by a sponsor shall include a disclosure statement spoken by the chief executive or principal decision maker of the sponsor and containing at least the following words: "[Name of sponsor] sponsored this ad." If the sponsor is a corporation that has the purpose of promoting social, educational, or political ideas, the advertisement shall also include a legible listing on the screen (or in the case of radio spoken) indicating that the viewer (or listener in the case of radio) may obtain additional information on the sponsor and the sponsor\'s donors from the appropriate board of elections, containing at least the following words: "For donor information contact [Name of board of elections with whom information filed]." In any television advertisement, an unobscured, full-screen picture containing the disclosing individual, either in photographic form or through the actual appearance of the disclosing individual on camera, must be featured throughout the duration of the disclosure statement. NC GS Section 163-278.39.',
			ND: 'Score: 0. North Dakota did not ban corporate independent expenditures and does not require disclosure of independent expenditures, electioneering communications or disclosure on ads.',
			OH: 'Ohio\'s legislature has not repealed the ban on corporate independent expenditures, but the Secretary of State\'s office issued a ruling in 2010 that lifted the ban and required disclosure by corporations making independent expenditures. Any independent expenditure must be reported. OH ST § 3517.105(B)(2). It does not require reporting of late independent expenditures. It does not require reporting of electioneering communications. The Secretary of State\'s ruling also required a disclaimer in the ad and identification of an officer or CEO of the corporation, with his or her name, address and website information also included (except for a radio ad which does not require the address of the corporation.) OH ST Section 3517.120(A)(2). The ruling was approved by a Legislative Committee but the disclosure provisions are no longer being enforced by the current Secretary of State.',
			OK: 'Score: 85. Oklahoma’s Ethics Commission enacted regulations repealing the ban on corporate independent expenditures. While there has been legislation to repeal the ban, the legislature has failed to act. Independent expenditure disclosure of over $500 applies to corporations but nothing new has been passed. OK ST Ethics Commission 257:10-1-11(a). Late independent expenditures of $500 or more must be reported within 24 hours. OK ST Ethics Commission 257:10-1-16 (a-b). Electioneering communication within the last 60 days before a general election and the last 30 days before a primary election must be disclosed. OK ST Ethics Commission 257:1-1-2.',
			OR: 'Score: 40. Oregon requires disclosure of independent expenditures if more than $750 is spent for or against a candidate. Until this year, the threshold was $100. OR ST 260.44. It has no late independent expenditure reporting. It has no electioneering communication reporting. It does not require disclosure on ads.',
			PA: 'Score: 80. Pennsylvania did not change its law or regulations other than administratively allowing corporations to make independent expenditures. A person other than a PAC that makes independent expenditures totaling more than $100 for or against a candidate or ballot question in a calendar year must disclose those activities on the reporting schedule applicable to PACs. PACs must report independent expenditures on their regular reporting schedules. 25 P.S. Section 3246(g). Independent expenditures of $500 or more made within the last fourteen days before an election must be reported within 24 hours. 25 P.S. Section 3248. There is no electioneering communication provision.',
			RI: 'Score: 90. Rhode Island’s Board of Elections issued a regulation saying that corporations could now make independent expenditures but had to follow the disclosure law that requires anyone making independent expenditures of $100 in a calendar year must file disclosure reports within seven days of the expenditure. RI ST Section 17-25-10 (b). There is no late independent expenditure reporting other than the seven day requirement. Electioneering communication is defined within the definition of “express advocacy” as “communications of slogans or individual words in context can have no other reasonable meaning than to urge the election or defeat of one or more clearly identified candidates, such as posters, bumper stickers and advertisements. Section 2, Number 6. of Reg 6126 adopted July 13, 2010. The regulation also requires electioneering communication disclosure and disclaimers on ads. Section 4 of Reg 6126 adopted July 13, 2010.',
			SC: 'Score: 30. South Carolina did not pass any legislation or rules in response to Citizens United but a federal court declared its independent expenditure law invalid since the definition of political committees was not constitutional. Because of this court case, South Carolina lacks campaign finance reporting of independent spending.South Carolina Citizens for Life v. Krawcheck ,759 F. Supp. 2d 708 (2010). The name of the person paying for the ad must be disclosed on the ad. SC ST Section 8-13-1354.',
			SD: 'Score: 100. South Dakota enacted an urgency bill was passed in 2010 that lifted the ban on corporate contributions to independent expenditure committees.\n\nIt also required disclosure of independent expenditures or electioneering communications of over $2,000 within 48 hours of the expenditure. The report must include anyone who owns or controls more than 10% of the entity if there are 20 or less people in charge of the organization. SD ST Section 12-27-16. It requires electioneering communications to be disclosed if made within 60 days of the election if over $2,000. D ST Section 12-27-1 (22). It also has a disclaimer provision, which requires disclosure of the source of the ad, its web address, as statement that the candidate did not authorize the ad. SD ST Section 12-27-16.',
			TN: 'Score: 40. Tennessee repealed its ban on corporate independent expenditures in 2010 and then in 2011 repealed its ban on direct corporate contributions to candidates. The law requires corporations to file independent expenditure disclosure reports when they make independent expenditures of more than $250. SD ST Section 2-10-105.t. There are no late independent expenditure reports required. There are no provisions dealing with electioneering communications. There are no disclaimer requirements.',
			TX: 'Score: 80. Texas repealed its ban on corporate independent expenditures and extended its independent expenditure reporting to corporations. Any independent expenditure of over $100 must be reported. Chapter 254, Election Code, Section 254.261. Late independent expenditures of over $1,000 must be reported by the next business day. Chapter 254, Election Code, Section 254.039. There is no electioneering communication disclosure requirement. Ads must indicate who paid for them. Chapter 254, Election Code, Section 255.01.',
			UT: 'Score: 70. Utah has not made any changes to its independent expenditure disclosure law since Citizens United was decided. Any corporation or committee that makes independent expenditures of at least $750 in a year must file disclosure statements. UT ST Section 20A-11-701(1) and UT ST Section 20A-11-602(1).\n\nIt has no late independent disclosure reporting. It has no electioneering communications sections. It requires disclosure on ads of the person paying for it and a disclaimer that it was not authorized by the candidate. UT ST Section 20A-11-901 (1) (a).',
			VT: 'Score: 100. Vermont has not made any changes to its disclosure laws since Citizens United. It requires disclosure of independent expenditures over $500 in the last 30 days before the election if made for media expenditures. The person making the expenditure must send a copy of the report to the candidate affected within 24 hours. VT ST T. 17 Section 2893. Vermont requires electioneering communications disclosure within 24 hours in the last 30 days before the election if $500 or more. VT ST T. 17 Sections 2891 and 2893. All ads must contain the name and address of the person who paid for the ad. VT ST T. 17 Section 2882.',
			VA: 'Score: 80. Virginia did not make any changes to its laws since Citizens United. It requires disclosure of independent expenditures if $1,000 or more for statewide and $200 or more for other candidates. VA ST Section 24.2-945.2. All independent expenditures of $1,000 or more for statewide and $200 or more for other candidates must be reported within 24 hours. VA ST Section 24.2-945.2 (A, B). Virginia has no electioneering communications provisions. It requires corporations or any other person that spends $1,000 or more ($200 for non-statewide candidates) on advertising to identify themselves in the ads and to say that the ad was not authorized by the candidate. VA ST Section 24.2-956.1.',
			WA: 'Score: 100 Washington requires disclosure of independent expenditures of $100 or more. WA ST 42.17A.255. It requires reporting of late independent expenditures of $1,000 or more made within the last 21 days before the election within 24 hours of the expenditure. WA ST 42.17.1003 (1). It has lowered the threshold for electioneering communications from $5,000 to $1,000 in 2011. WA ST 42.17.305. Washington requires all printed ads to contain the name and address of the sponsor of the ad. TV and radio ads need only contain the name of the person. WA ST 42.17.510.',
			WV: 'Score: 100 West Virginia repealed the corporate ban and passed legislation requiring disclosure of independent expenditures. Any entity making independent expenditures of over $1000 ($500 for local races) must file campaign statement that include anyone giving the entity more than $250 for the independent expenditure. WV ST 3-8-2. Late independent expenditures of $1,000 or more must be reported within 24 hours. WV ST 3-8-2 (c). In addition, any independent expenditure of $10,000 that has been contracted must be reported within 48 hours no matter how many days before the election. WV ST 3-8-2 (d). Anyone making electioneering communications of $5,000 or more if made within 30 days of a primary and 60 days of a general election must maintain records but is not required to file statements. WV ST 3-8-2 (f). Electioneering Communications are limited by case law to broadcast only. Ctr. for Individual Freedom, Inc. v. Ireland, 613 F. Supp. 2d 777, 781 n.5 (S.D.W. Va. 2009). Disclaimers must appear on the ad, indicating that the expenditure was not authorized by the candidate and who paid for the communications. WV ST 3-8-2 (e).',
			WI: 'Score: 100 Wisconsin responded to the Citizens United decision by passing emergency rules requiring disclosure of independent expenditures if over $25 or and a “paid for” disclaimer in the ad. The attorney general issued an opinion saying the corporate ban was invalid. Wisc. OAG 05-10. If an independent expenditure of over $20 is made within the last 15 days before the election, a report must be filed within 24 hours. WI ST 11.13 (6). Electioneering communication expenditures must be reported if within 30 days of the primary election or sixty days before the general election. GAB 1.28 (b).\n\nThe person making an independent expenditure must be identified in the ad. WI ST 11.30 (2) (a-b) and GAB 1.655.',
			WY: 'Score 30. Wyoming did not change its law after Citizens United even though the law bans corporate independent expenditures; thus, the prohibition is still on the books, but it is not being enforced. There is no independent expenditure disclosure in Wyoming.'
		});

		popcorn.stateExplorer({
			start: 72.1,
			end: 102.4
		});

		/*
			popcorn.defaults.stateExplorer = {
				state: 'MD'
			};

			popcorn.influenceExplorer({
				start: 1,
				end: 2
				//state: 'MD'
			});
		*/

		popcorn.media.addEventListener('keydown', function(evt) {
			if (evt.keyCode === 32) {
				evt.preventDefault();
			}
		}, true);

		window.addEventListener('keyup', function(evt) {
			if (evt.keyCode === 32) {
				if (popcorn.paused()) {
					popcorn.play();
				} else {
					popcorn.pause();
				}
			}
		}, true);
	}