function(frame)
{
    this.TakeHit(this.registeredHit_.AttackState
                ,this.registeredHit_.HitState
                ,this.registeredHit_.Flags
                ,this.registeredHit_.StartFrame
                ,this.registeredHit_.Frame
                ,this.registeredHit_.Damage
                ,this.registeredHit_.EnergyToAdd
                ,this.registeredHit_.IsProjectile
                ,this.registeredHit_.HitX
                ,this.registeredHit_.HitY
                ,this.registeredHit_.AttackDirection
                ,this.registeredHit_.Who
                ,this.registeredHit_.HitID
                ,this.registeredHit_.MoveOverrideFlags
                ,this.registeredHit_.AttackForceX
                ,this.registeredHit_.AttackForceY
                ,this.registeredHit_.OtherPlayer
                ,this.registeredHit_.BehaviorFlags
                ,this.registeredHit_.InvokedAnimationName
                ,this.registeredHit_.HitSound
                ,this.registeredHit_.BlockSound
                );

}