function(b,d,i){var k=d.audio&&d.video,l=!1;if(k)b=document.createElement("video"),d.videoBuffered="buffered"in b,l="loop"in b,i.capturingEvents("play,playing,waiting,paused,ended,durationchange,loadedmetadata,canplay,volumechange".split(",")),d.videoBuffered||(i.addPolyfill("mediaelement-native-fix",{f:"mediaelement",test:d.videoBuffered,d:["dom-support"]}),i.reTest("mediaelement-native-fix"));jQuery.webshims.register("mediaelement-core",function(b,d,i,q,p){var f=d.mediaelement,u=d.cfg.mediaelement,
x=function(a,c){var a=b(a),e={src:a.attr("src")||"",elem:a,srcProp:a.prop("src")};if(!e.src)return e;var g=a.attr("type");if(g)e.type=g,e.container=b.trim(g.split(";")[0]);else if(c||(c=a[0].nodeName.toLowerCase(),"source"==c&&(c=(a.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),g=f.getTypeForSrc(e.src,c))e.type=g,e.container=g,d.warn("you should always provide a proper mime-type using the source element. "+e.src+" detected as: "+g),b.nodeName(a[0],"source")&&a.attr("type",
g);if(g=a.attr("media"))e.media=g;return e},v=swfobject.hasFlashPlayerVersion("9.0.115"),w=function(){d.ready("mediaelement-swf",function(){if(!f.createSWF)d.modules["mediaelement-swf"].test=b.noop,d.reTest(["mediaelement-swf"],k)})};f.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],"audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":"mp4,mpg4,m4r,m4a,m4p,m4b,aac".split(","),"audio/wav":["wav"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"],"audio/fla":["flv","f4a","fla"],"application/x-mpegURL":["m3u8",
"m3u"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"],"application/x-mpegURL":["m3u8","m3u"],"video/MP2T":["ts"]}};f.mimeTypes.source=b.extend({},f.mimeTypes.audio,f.mimeTypes.video);f.getTypeForSrc=function(a,c){if(-1!=a.indexOf("youtube.com/watch?")||-1!=a.indexOf("youtube.com/v/"))return"video/youtube";
var a=a.split("?")[0].split("."),a=a[a.length-1],e;b.each(f.mimeTypes[c],function(c,b){if(-1!==b.indexOf(a))return e=c,!1});return e};f.srces=function(a,c){a=b(a);if(c)a.removeAttr("src").removeAttr("type").find("source").remove(),b.isArray(c)||(c=[c]),c.forEach(function(c){var b=q.createElement("source");"string"==typeof c&&(c={src:c});b.setAttribute("src",c.src);c.type&&b.setAttribute("type",c.type);c.media&&b.setAttribute("media",c.media);a.append(b)});else{var c=[],e=a[0].nodeName.toLowerCase(),
g=x(a,e);g.src?c.push(g):b("source",a).each(function(){g=x(this,e);g.src&&c.push(g)});return c}};b.fn.loadMediaSrc=function(a,c){return this.each(function(){c!==p&&(b(this).removeAttr("poster"),c&&b.attr(this,"poster",c));f.srces(this,a);b(this).mediaLoad()})};f.swfMimeTypes="video/3gpp,video/x-msvideo,video/quicktime,video/x-m4v,video/mp4,video/m4p,video/x-flv,video/flv,audio/mpeg,audio/aac,audio/mp4,audio/x-m4a,audio/m4a,audio/mp3,audio/x-fla,audio/fla,youtube/flv,jwplayer/jwplayer,video/youtube".split(",");
f.canSwfPlaySrces=function(a,c){var e="";v&&(a=b(a),c=c||f.srces(a),b.each(c,function(a,c){if(c.container&&c.src&&-1!=f.swfMimeTypes.indexOf(c.container))return e=c,!1}));return e};var t={};f.canNativePlaySrces=function(a,c){var e="";if(k){var a=b(a),g=(a[0].nodeName||"").toLowerCase();if(!t[g])return e;c=c||f.srces(a);b.each(c,function(c,b){if(b.type&&t[g].prop._supvalue.call(a[0],b.type))return e=b,!1})}return e};f.setError=function(a,c){c||(c="can't play sources");b(a).pause().data("mediaerror",
c);d.warn("mediaelementError: "+c);setTimeout(function(){b(a).data("mediaerror")&&b(a).trigger("mediaerror")},1)};var y=function(){var a;return function(c,b,g){d.ready("mediaelement-swf",function(){f.createSWF?f.createSWF(c,b,g):a||(a=!0,w(),y(c,b,g))})}}(),h=function(a,c,b,g,d){b||!1!==b&&c&&"flash"==c.isActive?(b=f.canSwfPlaySrces(a,g))?y(a,b,c):d?f.setError(a,!1):h(a,c,!1,g,!0):(b=f.canNativePlaySrces(a,g))?c&&"flash"==c.isActive&&f.setActive(a,"html5",c):d?(f.setError(a,!1),c&&"flash"==c.isActive&&
f.setActive(a,"html5",c)):h(a,c,!0,g,!0)},o=/^(?:embed|object|datalist)$/i,m=function(a,c){var e=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{}),g=f.srces(a),m=a.parentNode;clearTimeout(e.loadTimer);b.data(a,"mediaerror",!1);if(g.length&&m&&!(1!=m.nodeType||o.test(m.nodeName||"")))c=c||d.data(a,"mediaelement"),h(a,c,u.preferFlash||p,g)};b(q).bind("ended",function(a){var c=d.data(a.target,"mediaelement");(!l||c&&"html5"!=c.isActive||b.prop(a.target,"loop"))&&setTimeout(function(){!b.prop(a.target,
"paused")&&b.prop(a.target,"loop")&&b(a.target).prop("currentTime",0).play()},1)});l||d.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(a){var c=d.defineNodeNameProperty(a,"load",{prop:{value:function(){var a=d.data(this,"mediaelement");m(this,a);k&&(!a||"html5"==a.isActive)&&c.prop._supvalue&&c.prop._supvalue.apply(this,arguments)}}});t[a]=d.defineNodeNameProperty(a,"canPlayType",{prop:{value:function(c){var g="";k&&t[a].prop._supvalue&&(g=t[a].prop._supvalue.call(this,
c),"no"==g&&(g=""));!g&&v&&(c=b.trim((c||"").split(";")[0]),-1!=f.swfMimeTypes.indexOf(c)&&(g="maybe"));return g}}})});d.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,c=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{});clearTimeout(c.loadTimer);c.loadTimer=setTimeout(function(){m(a);a=null},9)}});i=function(){d.addReady(function(a,c){b("video, audio",a).add(c.filter("video, audio")).each(function(){b.browser.msie&&8<d.browserVersion&&b.prop(this,
"paused")&&!b.prop(this,"readyState")&&b(this).is('audio[preload="none"][controls]:not([autoplay])')?b(this).prop("preload","metadata").mediaLoad():m(this);if(k){var a,c,h=this,f=function(){var a=b.prop(h,"buffered");if(a){for(var c="",e=0,g=a.length;e<g;e++)c+=a.end(e);return c}},o=function(){var a=f();a!=c&&(c=a,b(h).triggerHandler("progress"))};b(this).bind("play loadstart progress",function(b){"progress"==b.type&&(c=f());clearTimeout(a);a=setTimeout(o,999)}).bind("emptied stalled mediaerror abort suspend",
function(b){"emptied"==b.type&&(c=!1);clearTimeout(a)})}})})};k?(d.isReady("mediaelement-core",!0),i(),v&&d.ready("WINDOWLOAD mediaelement",w)):d.ready("mediaelement-swf",i)})}