function(a,c,n){var k=c.audio&&c.video,p=!1;if(k)a=document.createElement("video"),c.videoBuffered="buffered"in a,p="loop"in a,n.capturingEvents("play,playing,waiting,paused,ended,durationchange,loadedmetadata,canplay,volumechange".split(",")),c.videoBuffered||(n.addPolyfill("mediaelement-native-fix",{f:"mediaelement",test:c.videoBuffered,d:["dom-support"]}),n.reTest("mediaelement-native-fix"));jQuery.webshims.register("mediaelement-core",function(a,c,n,u,r){var g=c.mediaelement,v=c.cfg.mediaelement,
w=function(b,d){var b=a(b),f={src:b.attr("src")||"",elem:b,srcProp:b.prop("src")};if(!f.src)return f;var i=b.attr("type");if(i)f.type=i,f.container=a.trim(i.split(";")[0]);else if(d||(d=b[0].nodeName.toLowerCase(),"source"==d&&(d=(b.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),i=g.getTypeForSrc(f.src,d))f.type=i,f.container=i,c.warn("you should always provide a proper mime-type using the source element. "+f.src+" detected as: "+i),a.nodeName(b[0],"source")&&b.attr("type",
i);if(i=b.attr("media"))f.media=i;return f},b=swfobject.hasFlashPlayerVersion("9.0.115"),j=function(){c.ready("mediaelement-swf",function(){if(!g.createSWF)c.modules["mediaelement-swf"].test=a.noop,c.reTest(["mediaelement-swf"],k)})};g.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],"audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":"mp4,mpg4,m4r,m4a,m4p,m4b,aac".split(","),"audio/wav":["wav"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"],"audio/fla":["flv","f4a","fla"],"application/x-mpegURL":["m3u8",
"m3u"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"],"application/x-mpegURL":["m3u8","m3u"],"video/MP2T":["ts"]}};g.mimeTypes.source=a.extend({},g.mimeTypes.audio,g.mimeTypes.video);g.getTypeForSrc=function(b,c){if(-1!=b.indexOf("youtube.com/watch?")||-1!=b.indexOf("youtube.com/v/"))return"video/youtube";
var b=b.split("?")[0].split("."),b=b[b.length-1],f;a.each(g.mimeTypes[c],function(a,c){if(-1!==c.indexOf(b))return f=a,!1});return f};g.srces=function(b,c){b=a(b);if(c)b.removeAttr("src").removeAttr("type").find("source").remove(),a.isArray(c)||(c=[c]),c.forEach(function(a){var c=u.createElement("source");"string"==typeof a&&(a={src:a});c.setAttribute("src",a.src);a.type&&c.setAttribute("type",a.type);a.media&&c.setAttribute("media",a.media);b.append(c)});else{var c=[],f=b[0].nodeName.toLowerCase(),
g=w(b,f);g.src?c.push(g):a("source",b).each(function(){g=w(this,f);g.src&&c.push(g)});return c}};a.fn.loadMediaSrc=function(b,c){return this.each(function(){c!==r&&(a(this).removeAttr("poster"),c&&a.attr(this,"poster",c));g.srces(this,b);a(this).mediaLoad()})};g.swfMimeTypes="video/3gpp,video/x-msvideo,video/quicktime,video/x-m4v,video/mp4,video/m4p,video/x-flv,video/flv,audio/mpeg,audio/aac,audio/mp4,audio/x-m4a,audio/m4a,audio/mp3,audio/x-fla,audio/fla,youtube/flv,jwplayer/jwplayer,video/youtube".split(",");
g.canSwfPlaySrces=function(c,d){var f="";b&&(c=a(c),d=d||g.srces(c),a.each(d,function(a,b){if(b.container&&b.src&&-1!=g.swfMimeTypes.indexOf(b.container))return f=b,!1}));return f};var t={};g.canNativePlaySrces=function(b,c){var f="";if(k){var b=a(b),i=(b[0].nodeName||"").toLowerCase();if(!t[i])return f;c=c||g.srces(b);a.each(c,function(a,c){if(c.type&&t[i].prop._supvalue.call(b[0],c.type))return f=c,!1})}return f};g.setError=function(b,d){d||(d="can't play sources");a(b).pause().data("mediaerror",
d);c.warn("mediaelementError: "+d);setTimeout(function(){a(b).data("mediaerror")&&a(b).trigger("mediaerror")},1)};var x=function(){var a;return function(b,f,i){c.ready("mediaelement-swf",function(){g.createSWF?g.createSWF(b,f,i):a||(a=!0,j(),x(b,f,i))})}}(),h=function(a,b,c,i,j){c||!1!==c&&b&&"flash"==b.isActive?(c=g.canSwfPlaySrces(a,i))?x(a,c,b):j?g.setError(a,!1):h(a,b,!1,i,!0):(c=g.canNativePlaySrces(a,i))?b&&"flash"==b.isActive&&g.setActive(a,"html5",b):j?(g.setError(a,!1),b&&"flash"==b.isActive&&
g.setActive(a,"html5",b)):h(a,b,!0,i,!0)},m=/^(?:embed|object|datalist)$/i,l=function(b,d){var f=c.data(b,"mediaelementBase")||c.data(b,"mediaelementBase",{}),i=g.srces(b),j=b.parentNode;clearTimeout(f.loadTimer);a.data(b,"mediaerror",!1);if(i.length&&j&&!(1!=j.nodeType||m.test(j.nodeName||"")))d=d||c.data(b,"mediaelement"),h(b,d,v.preferFlash||r,i)};a(u).bind("ended",function(b){var d=c.data(b.target,"mediaelement");(!p||d&&"html5"!=d.isActive||a.prop(b.target,"loop"))&&setTimeout(function(){!a.prop(b.target,
"paused")&&a.prop(b.target,"loop")&&a(b.target).prop("currentTime",0).play()},1)});p||c.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(e){var d=c.defineNodeNameProperty(e,"load",{prop:{value:function(){var a=c.data(this,"mediaelement");l(this,a);k&&(!a||"html5"==a.isActive)&&d.prop._supvalue&&d.prop._supvalue.apply(this,arguments)}}});t[e]=c.defineNodeNameProperty(e,"canPlayType",{prop:{value:function(c){var d="";k&&t[e].prop._supvalue&&(d=t[e].prop._supvalue.call(this,
c),"no"==d&&(d=""));!d&&b&&(c=a.trim((c||"").split(";")[0]),-1!=g.swfMimeTypes.indexOf(c)&&(d="maybe"));return d}}})});c.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,b=c.data(a,"mediaelementBase")||c.data(a,"mediaelementBase",{});clearTimeout(b.loadTimer);b.loadTimer=setTimeout(function(){l(a);a=null},9)}});n=function(){c.addReady(function(b,d){a("video, audio",b).add(d.filter("video, audio")).each(function(){a.browser.msie&&8<c.browserVersion&&a.prop(this,
"paused")&&!a.prop(this,"readyState")&&a(this).is('audio[preload="none"][controls]:not([autoplay])')?a(this).prop("preload","metadata").mediaLoad():l(this);if(k){var b,d,e=this,g=function(){var b=a.prop(e,"buffered");if(b){for(var c="",d=0,f=b.length;d<f;d++)c+=b.end(d);return c}},h=function(){var b=g();b!=d&&(d=b,a(e).triggerHandler("progress"))};a(this).bind("play loadstart progress",function(a){"progress"==a.type&&(d=g());clearTimeout(b);b=setTimeout(h,999)}).bind("emptied stalled mediaerror abort suspend",
function(a){"emptied"==a.type&&(d=!1);clearTimeout(b)})}})})};k?(c.isReady("mediaelement-core",!0),n(),b&&c.ready("WINDOWLOAD mediaelement",j)):c.ready("mediaelement-swf",n)})}