function(){
            checkForRedirect();
            renderMenu();
            renderUser();
            setCountUnreadMessages();
            setUserName();
            addBinding();
            forceShowLoginUrl();
        }