function () {
    it('should iterate over all plugins');

    it('should catch errors generated by the plugins');

    it('should handle plugins that doesnst return content');

    it('should callback with one error when things breaks');

    it('should callback the newly generated collection');
  }