function(){
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
    $(".nano").nanoScroller();
  }