function(state){
		if(this.stateful)
		{
			this.suspendEvents();
			if(state && state.collapsed)
			{
				this.collapsed=state.collapsed;				
			}
			if(this.statefulNodes)
			{
				this.restoreNodes(state.nodes);				
			}
			if(state.customHostFilters)
			{
				this.store.customHostFilters=state.customHostFilters;
			}
			if(state.customServiceFilters)
			{
				this.store.customServiceFilters=state.customServiceFilters;
			}
			this.resumeEvents();
		}
	}