function anonymous(yytext,yyleng,yylineno,yy,yystate,$$,_$) {

var $0 = $$.length - 1;
switch (yystate) {
case 1:return [];
break;
case 2:return $$[$0-1];
break;
case 3:this.$ = $$[$0];
break;
case 4:this.$ = [$$[$0]];
break;
case 5:this.$ = $$[$0-2]; $$[$0-2].push($$[$0]);
break;
case 6:this.$ = $$[$0-1];
break;
case 7:this.$ = $$[$0];
break;
case 8:this.$ = $$[$0];
break;
case 9:this.$ = new yy.Return($$[$0]);
break;
case 10:this.$ = new yy.Block($$[$0-1]);
break;
case 11:this.$ = $$[$0];
break;
case 12:this.$ = $$[$0];
break;
case 13:this.$ = $$[$0];
break;
case 14:this.$ = $$[$0];
break;
case 15:this.$ = $$[$0];
break;
case 16:this.$ = $$[$0];
break;
case 17:this.$ = $$[$0];
break;
case 18:this.$ = $$[$0];
break;
case 19:this.$ = $$[$0];
break;
case 20:this.$ = $$[$0-1];
break;
case 21:this.$ = new yy.If($$[$0-3], $$[$0-1], null);
break;
case 22:this.$ = new yy.If($$[$0-5], $$[$0-3], $$[$0-1]);
break;
case 23:this.$ = new yy.While($$[$0-3], $$[$0-1]);
break;
case 24:this.$ = new yy.For($$[$0-5], $$[$0-3], $$[$0-1]);
break;
case 25:this.$ = new yy.Assign($$[$0-2], $$[$0]);
break;
case 26:this.$ = new yy.Operator($$[$0-1], $$[$0-2], $$[$0]);
break;
case 27:this.$ = new yy.Operator($$[$0-1], $$[$0-2], $$[$0]);
break;
case 28:this.$ = new yy.Operator($$[$0-1], $$[$0-2], $$[$0]);
break;
case 29:this.$ = new yy.Call($$[$0-3], null, $$[$0-1]);
break;
case 30:this.$ = new yy.Function($$[$0-5], $$[$0-3], $$[$0-1]);
break;
case 31:this.$ = new yy.Class($$[$0-2], $$[$0-1]);
break;
case 32:this.$ = [];
break;
case 33:this.$ = [$$[$0]];
break;
case 34:this.$ = $$[$0-2]; $$[$0-2].push($$[$0]);
break;
case 35:this.$ = $$[$0];
break;
case 36:this.$ = $$[$0];
break;
case 37:this.$ = new yy.Identifier($$[$0]);
break;
case 38:this.$ = new yy.Number($$[$0]);
break;
case 39:this.$ = new yy.String($$[$0]);
break;
case 40:this.$ = new yy.Const($$[$0])
break;
}
}