fvar Q=Q.COLLADA,O={up_axis:1,images:[],effects:[],materials:[],meshes:[],scenes:[],lights:[],cameras:[],animations:[]};if(Q.asset){var Ma=Q.asset.up_axis.$;"X_UP"===Ma?O.up_axis=0:"Y_UP"===Ma?O.up_axis=1:"Z_UP"===Ma&&(O.up_axis=2)}var gb=O.up_axis;if(Q.library_images&&(Q.library_images.image&&!Q.library_images.image.length&&(Q.library_images.image=[Q.library_images.image]),Q.library_images.image.length))for(var hb=Q.library_images.image,Na=0,qb=hb.length;Na<qb;Na++){var Oa=hb[Na],ib=Oa["@id"],Ic=
Oa["@name"],$b=Oa.init_from;if($b.$){var ra=$b.$;a!==w&&-1!==ra.lastIndexOf("/")&&(ra=ra.substr(ra.lastIndexOf("/")+1));a!==w&&-1!==ra.lastIndexOf("\\")&&(ra=ra.substr(ra.lastIndexOf("\\")+1));O.images[ib]={source:ra,id:ib,name:Ic}}}var jb,rb,ac,W,Pa,ka,Qa,da,P,X,T,Da,ha,Ra,Sa,Z,aa;if(Q.library_effects){var Ta=Q.library_effects.effect;Ta&&!Ta.length&&(Ta=[Ta]);rb=0;for(ac=Ta.length;rb<ac;rb++){var Db=Ta[rb];jb=Db["@id"];var U={};U.id=jb;U.surfaces=[];U.samplers=[];(da=Db.profile_COMMON.newparam)&&
!da.length&&(da=[da]);if(da){S=0;for(ca=da.length;S<ca;S++){var sa=da[S],Ua=sa["@sid"];if(sa.surface){U.surfaces[Ua]={};var bc=sa.surface.init_from.$;"object"===typeof O.images[bc]&&(U.surfaces[Ua].source=a+"/"+O.images[bc].source)}else if(sa.sampler2D&&(U.samplers[Ua]={},U.samplers[Ua].source=sa.sampler2D.source.$,sa.sampler2D.minfilter&&(U.samplers[Ua].minfilter=sa.sampler2D.minfilter.$),sa.sampler2D.magfilter))U.samplers[Ua].magfiter=sa.sampler2D.magfilter.$}}var va=Db.profile_COMMON.technique;
va&&!va.length&&(va=[va]);U.material={textures_ref:[]};W=0;for(Pa=va.length;W<Pa;W++){g=va[W].blinn;g||(g=va[W].phong);g||(g=va[W].lambert);if(g)for(var ea in g){var sb=g[ea],ta=c(sb),cc=d(sb),dc=!sb.texture?!1:sb.texture["@texture"];!1!==ta&&3<ta.length&&ta.pop();"emission"==ea?!1!==ta&&(U.material.ambient=ta):"ambient"!=ea&&("diffuse"==ea?!1!==ta&&(U.material.color=ta):"specular"==ea?!1!==ta&&(U.material.specular=ta):"shininess"==ea&&!1!==cc&&(U.material.shininess=cc));if(!1!==dc){var Va=U.surfaces[U.samplers[dc].source].source;
"emission"==ea?U.material.textures_ref.push({image:Va,type:q.texture.map.AMBIENT}):"ambient"==ea?U.material.textures_ref.push({image:Va,type:q.texture.map.AMBIENT}):"diffuse"==ea?U.material.textures_ref.push({image:Va,type:q.texture.map.COLOR}):"specular"==ea?U.material.textures_ref.push({image:Va,type:q.texture.map.SPECULAR}):"shininess"!=ea&&("reflective"==ea?U.material.textures_ref.push({image:Va,type:q.texture.map.REFLECT}):"reflectivity"!=ea&&"transparent"==ea&&U.material.textures_ref.push({image:Va,
type:q.texture.map.ALPHA}))}}O.effects[jb]=U}}}var Eb=b.getAllOf(Q,"instance_geometry"),tb=[];if(Eb.length){u=0;for(E=Eb.length;u<E;u++){var ec=Eb[u],Fb=b.getAllOf(ec,"instance_material");if(Fb.length){V=0;for(na=Fb.length;V<na;V++){var fc=Fb[V],Jc=fc["@symbol"],Kc=fc["@target"].substr(1);tb[ec["@url"].substr(1)+":"+Jc]=Kc}}}}var Gb=Q.library_materials;if(Gb&&Gb.material){var Wa=Gb.material;Wa&&!Wa.length&&(Wa=[Wa]);F=0;for(H=Wa.length;F<H;F++){var Hb=Wa[F],Lc=Hb["@id"],Mc=Hb["@name"],gc=Hb.instance_effect;
gc&&(jb=gc["@url"].substr(1),O.materials.push({id:Lc,name:Mc,mat:O.effects[jb].material}))}}var hc=Q.library_geometries,Xa;if(hc){var ua=hc.geometry;ua&&!ua.length&&(ua=[ua]);if(ua.length)for(var kb=0,Nc=ua.length;kb<Nc;kb++){var ma={id:w,points:[],parts:[]},Ya=ua[kb].mesh;if(Ya){Xa=ua[kb]["@id"];n=ua[kb]["@name"];var Za=Ya.source;Za&&!Za.length&&(Za=[Za]);for(var R=[],Ib=0,Oc=Za.length;Ib<Oc;Ib++){var ub=Za[Ib];o=ub["@id"];var Pc=ub["@name"],Jb=ub.float_array;Jb&&(R[o]={id:o,name:Pc,data:e.floatDelimArray(Jb.$?
Jb.$:""," ")});var Kb=ub.technique_common.accessor;Kb&&(R[o].count=Kb["@count"]|0,R[o].stride=Kb["@stride"]|0,R[o].count&&(R[o].data=e.repackArray(R[o].data,R[o].stride,R[o].count)))}var Lb=Ya.vertices,lb=null,Mb=null,Ea=null,Fa=null,Ga=null;if(Lb&&(Mb=Lb["@id"],(P=Lb.input)&&!P.length&&(P=[P]),P)){ka=0;for(Qa=P.length;ka<Qa;ka++)X=P[ka],"POSITION"===X["@semantic"]&&(lb=X["@source"].substr(1))}var oa=Ya.triangles;oa&&!oa.length&&(oa=[oa]);if(oa){W=0;for(Pa=oa.length;W<Pa;W++){aa={material:0,faces:[],
normals:[],texcoords:[],colors:[]};var Qc=parseInt(oa[W]["@count"],10);(P=oa[W].input)&&!P.length&&(P=[P]);T=[];if(P.length){ka=0;for(Qa=P.length;ka<Qa;ka++)X=P[ka],Z=parseInt(X["@offset"],10),r=X["@source"].substr(1),"VERTEX"===X["@semantic"]?(r===Mb&&(r=lb),T[Z]=0):"NORMAL"===X["@semantic"]?(Ea=r,R[Ea].count&&(T[Z]=1)):"TEXCOORD"===X["@semantic"]?(Ga=r,R[Ga].count&&(T[Z]=2)):"COLOR"===X["@semantic"]?(Fa=r,R[Fa].count&&(T[Z]=3)):T[Z]=4}C=T.length;m=Xa+":"+oa[W]["@material"];null===m?aa.material=
0:tb[m]===w?(s("missing material ["+m+"]@"+Xa+"?"),aa.material=0):aa.material=tb[m];var ic=oa[W].p,wa=[];ic&&(wa=e.intDelimArray(ic.$," "));if(wa.length&&(y=wa.length/T.length/3,y===Qc)){0===ma.points.length&&(ma.points=R[lb].data);u=Z=0;E=wa.length;for(z=T.length;u<E;u+=3*z){t=[];A=[];D=[];ia=[];for(V=0;V<3*z;V++){var vb=V%z;0===T[vb]?A.push(wa[u+V]):1===T[vb]?t.push(wa[u+V]):2===T[vb]?D.push(wa[u+V]):3===T[vb]&&ia.push(wa[u+V])}A.length&&(aa.faces.push(A),3===t.length&&aa.normals.push([b.fixuaxis(O.up_axis,
R[Ea].data[t[0]]),b.fixuaxis(O.up_axis,R[Ea].data[t[1]]),b.fixuaxis(O.up_axis,R[Ea].data[t[2]])]),3===D.length&&aa.texcoords.push([R[Ga].data[D[0]],R[Ga].data[D[1]],R[Ga].data[D[2]]]),3===ia.length&&aa.colors.push([R[Fa].data[ia[0]],R[Fa].data[ia[1]],R[Fa].data[ia[2]]]))}}ma.parts.push(aa)}}var ja=Ya.polylist;ja||(ja=Ya.polygons);ja&&!ja.length&&(ja=[ja]);if(ja){W=0;for(Pa=ja.length;W<Pa;W++){aa={material:0,faces:[],normals:[],texcoords:[],colors:[]};var jc=parseInt(ja[W]["@count"],10);(P=ja[W].input)&&
!P.length&&(P=[P]);T=[];if(P.length){ka=0;for(Qa=P.length;ka<Qa;ka++){X=P[ka];var Nb=X["@offset"];null===Nb&&(Nb=X["@idx"]);Z=parseInt(Nb,10);r=X["@source"].substr(1);"VERTEX"===X["@semantic"]?(r===Mb&&(r=lb),T[Z]=0):"NORMAL"===X["@semantic"]?(Ea=r,T[Z]=1):"TEXCOORD"===X["@semantic"]?(Ga=r,T[Z]=2):"COLOR"===X["@semantic"]?(Fa=r,T[Z]=3):T[Z]=4}}var kc=ja[W].vcount,$a=[];kc&&($a=e.intDelimArray(kc.$," "));m=Xa+":"+ja[W]["@material"];aa.material=m===w?0:tb[m];var mb=ja[W].p;C=T.length;var xa=[];if(1<
mb.length&&!$a.length){S=0;for(ca=mb.length;S<ca;S++){var lc=e.intDelimArray(mb[S].$," ");$a[S]=parseInt(lc.length/C,10);xa=xa.concat(lc)}}else mb&&(xa=e.intDelimArray(mb.$," "));if(xa.length)if(y=$a.length,y!==jc)s("poly vcount data doesn't add up, skipping object load: "+y+" !== "+jc);else{0===ma.points.length&&(ma.points=R[lb].data);u=Z=0;for(E=$a.length;u<E;u++){t=[];A=[];D=[];ia=[];V=0;for(na=$a[u]*C;V<na;V++)0===T[V%C]?A.push(xa[Z]):1===T[V%C]?t.push(xa[Z]):2===T[V%C]?D.push(xa[Z]):3===T[V%
C]&&ia.push(xa[Z]),Z++;var ab;if(A.length){aa.faces.push(A);if(t.length){$=[];G=0;for(J=t.length;G<J;G++)$.push(b.fixuaxis(O.up_axis,R[Ea].data[t[G]]));aa.normals.push($)}if(D.length){ab=[];G=0;for(J=D.length;G<J;G++)ab.push(R[Ga].data[D[G]]);aa.texcoords.push(ab)}if(ia.length){ab=[];G=0;for(J=ia.length;G<J;G++)ab.push(R[Fa].data[ia[G]]);aa.colors.push(ab)}}}}ma.parts.push(aa)}}if(1!==gb){u=0;for(E=ma.points.length;u<E;u++)ma.points[u]=b.fixuaxis(O.up_axis,ma.points[u])}ma.id=Xa;O.meshes.push(ma)}}}var mc=
Q.library_cameras;if(mc){(Ra=mc.camera)&&!Ra.length&&(Ra=[Ra]);L=0;for(M=Ra.length;L<M;L++){ha=Ra[L];var Rc=ha["@id"],wb=0,xb=0,yb=0;ha.optics&&(ha.optics.technique_common&&ha.optics.technique_common.perspective)&&(wb=ha.optics.technique_common.perspective.yfov,xb=ha.optics.technique_common.perspective.znear,yb=ha.optics.technique_common.perspective.zfar);var Ob,Pb,Qb;if(!wb&&!xb&&!yb){(da=ha.param)&&!da.length&&(da=[da]);u=0;for(E=da.length;u<E;u++){var Rb=da[u].$,Sb=da[u]["@name"];"YFOV"==Sb?Ob=
parseFloat(Rb):"ZNEAR"==Sb?Pb=parseFloat(Rb):"ZFAR"==Sb&&(Qb=parseFloat(Rb))}}else Ob=wb?parseFloat(wb.$):60,Pb=xb?parseFloat(xb.$):0.1,Qb=yb?parseFloat(yb.$):1E3;O.cameras.push({id:Rc,targeted:!1,fov:parseFloat(Ob),nearclip:parseFloat(Pb),farclip:parseFloat(Qb)})}}var nc=Q.library_lights,Ha;if(nc){var Ia=nc.light;Ia&&!Ia.length&&(Ia=[Ia]);var oc={point:"point",directional:"directional",spot:"spot"};if(Ia)for(var Tb=0,Sc=Ia.length;Tb<Sc;Tb++){Ha=Ia[Tb];var pc,nb,zb;for(zb in oc)if(Ha.technique_common[zb]){pc=
zb;nb=Ha.technique_common[zb];break}if(nb){var Tc=oc[pc]||"point",qc=Ha["@id"],rc=nb.intensity,Uc=rc?parseFloat(rc.$):1,sc=nb.distance,Vc=sc?parseFloat(sc.$):10,tc=nb.color,ia=[1,1,1];tc&&(ia=e.floatDelimArray(tc.$," "));O.lights.push({id:qc,name:qc,type:Tc,method:q.light.method.STATIC,diffuse:ia,specular:[0,0,0],distance:Vc,intensity:Uc})}}}var uc=Q.library_visual_scenes;if(uc){var bb=null;(bb=uc.visual_scene)&&!bb.length&&(bb=[bb]);for(var Ub=0,Wc=bb.length;Ub<Wc;Ub++){Sa=bb[Ub];var ya={id:Sa["@id"],
sceneObjects:[],cameras:[],lights:[],parentMap:[]},pa=[],cb=[],za,Vb,la,ba,$,vc=Q.library_nodes;if(vc){var db=vc.node;db&&!db.length&&(db=[db]);pa=[];u=0;for(E=db.length;u<E;u++)Vb=db[u],mnodeId=Vb["@id"],pa[la]=Vb;for(za=[Sa];za.length;){ba=za.pop();if(ba.node&&(($=ba.node)&&!$.length&&($=[$]),$)){u=0;for(E=$.length;u<E;u++)za.push($[u])}if(ba.instance_node){var eb=ba.instance_node;eb&&!eb.length&&(eb=[eb]);u=0;for(E=eb.length;u<E;u++){var Wb=eb[u]["@url"].substr(1);pa[Wb]&&(ba.node&&ba.node.length&&
(ba.node=[ba.node]),ba.node?ba.node.push(pa[Wb]):ba.node=[pa[Wb]])}}}}for(za=[Sa];za.length;)if(ba=za.pop(),ba.node&&(($=ba.node)&&!$.length&&($=[$]),$)){u=0;for(E=$.length;u<E;u++)$[u].parentNode=ba,cb.push($[u]),za.push($[u])}if(cb.length)for(var ob=0,Xc=cb.length;ob<Xc;ob++){var Aa=cb[ob],Ba=Aa.instance_geometry;Ha=cb[ob].instance_light;ha=cb[ob].instance_camera;la=Aa["@id"];var fa=Aa["@name"],ga=b.cl_getInitalTransform(O.up_axis,Aa);2===gb&&(ga.rotation=b.quaternionFilterZYYZ(ga.rotation,ha?[-90,
0,0]:w));var pb=null,Y=null,fb;if(Ba){Ba&&!Ba.length&&(Ba=[Ba]);u=0;for(E=Ba.length;u<E;u++)if(n=Ba[u]["@url"].substr(1),Y={},Y.name=(fa?fa:la)+(u?u:""),Y.id=(la?la:fa)+(u?u:""),Y.meshId=Xa,Y.meshName=n,pb||(Y.position=ga.position,Y.rotation=ga.rotation,Y.scale=ga.scale,Y.matrix=ga.matrix),ya.sceneObjects.push(Y),pa[Y.id]=!0,Aa.parentNode)(fb=Aa.parentNode["@id"])&&pa[fb]?ya.parentMap.push({parent:fb,child:Y.id}):1<Ba.length&&(pb?pa[pb.id]&&ya.parentMap.push({parent:pb.id,child:Y.id}):(pb=Y,Y={}))}else if(ha){var Yc=
ha["@url"].substr(1);ya.cameras.push({name:fa?fa:la,id:fa?fa:la,source:Yc,position:ga.position,rotation:ga.rotation})}else if(Ha){var Zc=Ha["@url"].substr(1);ya.lights.push({name:fa?fa:la,id:fa?fa:la,source:Zc,position:ga.position,rotation:ga.rotation||[0,0,0]})}else Y={position:ga.position,rotation:ga.rotation,scale:ga.scale,matrix:ga.matrix},Y.name=fa?fa:la,Y.id=la?la:fa,ya.sceneObjects.push(Y),pa[Y.id]=!0,Aa.parentNode&&(fb=Aa.parentNode["@id"])&&pa[fb]&&ya.parentMap.push({parent:fb,child:Y.id})}O.scenes.push(ya)}}var wc=
Q.library_animations,qa;if(wc){var Ja=wc.animation;Ja&&!Ja.length&&(Ja=[Ja]);if(Ja)for(var Xb=0,$c=Ja.length;Xb<$c;Xb++){var Ab=Ja[Xb];qa=Ab["@id"];O.animations[qa]={};O.animations[qa].sources=[];var Ka=Ab.source;Ka&&!Ka.length&&(Ka=[Ka]);if(Ka.length){K=0;for(N=Ka.length;K<N;K++){var Ca=Ka[K];o=Ca["@id"];var xc=Ca.technique_common,Bb=null,yc=null;Ca.name_array?Bb=e.textDelimArray(Ca.name_array.$," "):Ca.Name_array?Bb=e.textDelimArray(Ca.Name_array.$," "):Ca.float_array&&(yc=e.floatDelimArray(Ca.float_array.$,
" "));var Yb=0,zc="",Cb=1;if(xc){g=xc;var Zb=g.accessor,Yb=parseInt(Zb["@count"],10),zc=Zb["@source"].substr(1),Ac=Zb["@stride"];Ac&&(Cb=parseInt(Ac,10))}O.animations[qa].sources[o]={data:Bb?Bb:yc,count:Yb,source:zc,stride:Cb};1!==Cb&&(O.animations[qa].sources[o].data=e.repackArray(O.animations[qa].sources[o].data,Cb,Yb))}}(Da=Ab.sampler)&&!Da.length&&(Da=[Da]);if(Da){O.animations[qa].samplers=[];K=0;for(N=Da.length;K<N;K++){var Bc=Da[K],ad=Bc["@id"];(P=Bc.input)&&!P.length&&(P=[P]);if(P){var Cc=
[];x=0;for(E=P.length;x<E;x++)X=P[x],Cc[X["@semantic"]]=X["@source"].substr(1);O.animations[qa].samplers[ad]=Cc}}}var La=Ab.channel;La&&!La.length&&(La=[La]);if(La){O.animations[qa].channels=[];L=0;for(M=La.length;L<M;L++){var Dc=La[L],bd=Dc["@source"].substr(1),Ec=Dc["@target"],Fc=Ec.split("/"),cd=Fc[0],Gc=Fc[1].split(".");O.animations[qa].channels.push({source:bd,target:Ec,targetName:cd,paramName:Gc[0],typeName:Gc[1]})}}}}var Hc=Q.scene;if(Hc&&(Sa=Hc.instance_visual_scene)){var dd=Sa["@url"].substr(1);
O.scene=dd}return O}var w=h.undef,q=h.enums,n=h.GLCore,s=h.log,b={fixuaxis:function(b,a){if(0===b)return[a[1],a[0],a[2]];if(1===b)return a;if(2===b)return[a[0],a[2],-a[1]]},fixscaleaxis:function(b,a){if(0===b)return[a[1],a[0],a[2]];if(1===b)return a;if(2===b)return[a[0],a[2],a[1]]},fixukaxis:function(b,a,c,d){return a===q.motion.POS&&c===q.motion.Z&&b===q.motion.Z?-d:d},getAllOf:function(b,a){for(var c=[b],d=[],e,g,o,m;c.length;)for(g in e=c.pop(),e)if(e.hasOwnProperty(g)){if(g===a)if(e[g].length){o=
