function populateEditPages() {
		$newHTML = '<div id="pods-parts-search"><label for="pods-parts-search-box">Search:</label><input id="pods-parts-search-box" name="pods-parts-search-box" type="text" /><input id="pods-parts-search-box-submit" name="pods-parts-search-box-submit" class="button-secondary" value="Search Pages" /></div>';
		$newHTML+= '<div class="clear"></div>';
		$newHTML+= '<div class="tablenav top lightgraybackground">';
		$newHTML+= '<div id="pods-parts-display-per-page" class="left">';
		$newHTML+= '<label for="pods-parts-display-per-page-select">Display Per Page:</label>';
		$newHTML+= '<select id="pods-parts-display-per-page-select" name="pods-parts-display-per-page-select">';
		$newHTML+= '<option value="40">40</option>';
		$newHTML+= '<option value="20">20</option>';
		$newHTML+= '<option value="10">10</option>';
		$newHTML+= '</select>';
		$newHTML+= '</div>';
		$newHTML+= '<div class="pods-parts-pagination">';
		$newHTML+= '<div class="tablenav-pages">';
		$newHTML+= '<span class="pagination-links">';
		$newHTML+= '<a class="first-page disabled" href="#" title="Go to the first page">&laquo;</a>';
		$newHTML+= '<a class="prev-page disabled" href="#" title="Go to the previous page">‹</a>';
		$newHTML+= '<span class="paging-input">';
		$newHTML+= '<input class="current-page" type="text" size="2" value="1" name="paged" title="Current page" />';
		$newHTML+= ' of ';
		$newHTML+= '<span class="total-pages">10 </span>';
		$newHTML+= '</span>';
		$newHTML+= '<a class="next-page" href="#" title="Go to the next page">›</a>';
		$newHTML+= '<a class="last-page" href="#" title="Go to the last page">»</a>';
		$newHTML+= '</span>';
		$newHTML+= '</div>';
		$newHTML+= '</div>';
		$newHTML+= '</div>';
		$newHTML+= '<table style="width: 100%">';
		$newHTML+= '<tr>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '</tr>';
		$newHTML+= '<tr>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '<td>';
		$newHTML+= '<div class="bluehighlight">';
		$newHTML+= '<span class="blue"><a href="#">file/photo/single</a></span>';
		$newHTML+= '<span class="gray">Display</span><span class="actions"><a href="#" class="editpodspart">Edit</a> | <a href="#" class="deletepodspart">Delete</a></span>';
		$newHTML+= '</div>';
		$newHTML+= '</td>';
		$newHTML+= '</tr>';
		$newHTML+= '</table>';
		$newHTML+= '<div class="tablenav top lightgraybackground">';
		$newHTML+= '<div id="pods-parts-display-per-page" class="left">';
		$newHTML+= '<label for="pods-parts-display-per-page-select">Display Per Page</label>';
		$newHTML+= '<select id="pods-parts-display-per-page-select" name="pods-parts-display-per-page-select">';
		$newHTML+= '<option value="40">40</option>';
		$newHTML+= '<option value="20">20</option>';
		$newHTML+= '<option value="10">10</option>';
		$newHTML+= '</select>';
		$newHTML+= '</div>';
		$newHTML+= '<div class="pods-parts-pagination">';
		$newHTML+= '<div class="tablenav-pages">';
		$newHTML+= '<span class="pagination-links">';
		$newHTML+= '<a class="first-page disabled" href="#" title="Go to the first page">&laquo;</a>';
		$newHTML+= '<a class="prev-page disabled" href="#" title="Go to the previous page">‹</a>';
		$newHTML+= '<span class="paging-input">';
		$newHTML+= '<input class="current-page" type="text" size="2" value="1" name="paged" title="Current page" />';
		$newHTML+= ' of ';
		$newHTML+= '<span class="total-pages">10 </span>';
		$newHTML+= '</span>';
		$newHTML+= '<a class="next-page" href="#" title="Go to the next page">›</a>';
		$newHTML+= '<a class="last-page" href="#" title="Go to the last page">»</a>';
		$newHTML+= '</span>';
		$newHTML+= '</div>';
		$newHTML+= '</div>';
		$newHTML+= '</div>';
		$('#pods-parts-popup').html($newHTML);
		updateButtonText('Update Pods Page');
	}