function() {
	this._checks = {};
	this._mStyle = goog.dom.createElement(npf.userAgent.Support.MOD).style;

	this._tests = goog.object.create(
		npf.userAgent.Support.Property.APPLICATION_CACHE, this._testApplicationCache,
		npf.userAgent.Support.Property.AUDIO, this._testAudio,
		npf.userAgent.Support.Property.BACKGROUND_SIZE, this._testBackgroundSize,
		npf.userAgent.Support.Property.BORDER_IMAGE, this._testBorderImage,
		npf.userAgent.Support.Property.BORDER_RADIUS, this._testBorderRadius,
		npf.userAgent.Support.Property.BOX_SHADOW, this._testBoxShadow,
		npf.userAgent.Support.Property.CANVAS, this._testCanvas,
		npf.userAgent.Support.Property.CANVAS_TEXT, this._testCanvasText,
		npf.userAgent.Support.Property.CSS_ANIMATIONS, this._testCssAnimations,
		npf.userAgent.Support.Property.CSS_COLUMNS, this._testCssColumns,
		npf.userAgent.Support.Property.CSS_GRADIENTS, this._testCssGradients,
		npf.userAgent.Support.Property.CSS_REFLECTIONS, this._testCssReflections,
		npf.userAgent.Support.Property.CSS_TRANSFORMS, this._testCssTransforms,
		npf.userAgent.Support.Property.CSS_TRANSFORMS_3D, this._testCssTransforms3d,
		npf.userAgent.Support.Property.CSS_TRANSITIONS, this._testCssTransitions,
		npf.userAgent.Support.Property.DRAG_AND_DROP, this._testDragAndDrop,
		npf.userAgent.Support.Property.FLEX_BOX, this._testFlexbox,
		npf.userAgent.Support.Property.FLEX_BOX_LEGACY, this._testFlexboxLegacy,
		npf.userAgent.Support.Property.FONT_FACE, this._testFontFace,
		npf.userAgent.Support.Property.GENERATED_CONTENT, this._testGeneratedContent,
		npf.userAgent.Support.Property.GEOLOCATION, this._testGeolocation,
		npf.userAgent.Support.Property.HASH_CHANGE, this._testHashChange,
		npf.userAgent.Support.Property.HISTORY, this._testHistory,
		npf.userAgent.Support.Property.HSLA, this._testHsla,
		npf.userAgent.Support.Property.INDEXED_DB, this._testIndexedDb,
		npf.userAgent.Support.Property.INLINE_SVG, this._testInlineSvg,
		npf.userAgent.Support.Property.INPUT, this._webforms,
		npf.userAgent.Support.Property.INPUT_TYPES, this._webforms,
		npf.userAgent.Support.Property.LOCAL_STORAGE, this._testLocalStorage,
		npf.userAgent.Support.Property.MULTIPLE_BACKGROUNDS, this._testMultipleBackgrounds,
		npf.userAgent.Support.Property.OPACITY, this._testOpacity,
		npf.userAgent.Support.Property.POST_MESSAGE, this._testPostMessage,
		npf.userAgent.Support.Property.RGBA, this._testRgba,
		npf.userAgent.Support.Property.SESSION_STORAGE, this._testSessionStorage,
		npf.userAgent.Support.Property.SMIL, this._testSmil,
		npf.userAgent.Support.Property.SVG, this._testSvg,
		npf.userAgent.Support.Property.SVG_CLIP_PATHS, this._testSvgClipPaths,
		npf.userAgent.Support.Property.TEXT_SHADOW, this._testTextShadow,
		npf.userAgent.Support.Property.TOUCH, this._testTouch,
		npf.userAgent.Support.Property.VIDEO, this._testVideo,
		npf.userAgent.Support.Property.WEB_GL, this._testWebgl,
		npf.userAgent.Support.Property.WEB_SOCKETS, this._testWebSockets,
		npf.userAgent.Support.Property.WEB_SQL_DATABASE, this._testWebSqlDatabase,
		npf.userAgent.Support.Property.WEB_WORKERS, this._testWebWorkers
	);
}