function() {
    return {
      colorboxInline: false,
      colorboxIframe: false,
      colorboxGroupId: '',
      colorboxTitle: '',
      colorboxWidth: false,
      colorboxHeight: false,
      colorboxMaxWidth: false,
      colorboxMaxHeight: false,
      colorboxSlideshow: false,
      colorboxSlideshowAuto: false,
      colorboxScalePhotos: false,
      colorboxPreloading: false,
      colorboxOverlayClose: false,
      colorboxLoop: false,
      colorboxEscKey: true,
      colorboxArrowKey:true,
      colorboxScrolling:false,
      colorboxOpacity:'0.85',
      colorboxTransition:'elastic',
      colorboxSpeed:'350',
      colorboxSlideshowSpeed:'2500',
      colorboxClose: 'close',
      colorboxNext:'next',
      colorboxPrevious:'previous',
      colorboxSlideshowStart:'start slideshow',
      colorboxSlideshowStop:'stop slideshow',
      colorboxCurrent:'{current} of {total} images',

      colorboxImageMaxWidth: false,
      colorboxImageMaxHeight: false,
      colorboxImageHeight: false,
      colorboxImageWidth:false,

      colorboxLinkHeight: false,
      colorboxLinkWidth: false,

      colorboxInitialHeight: 100,
      colorboxInitialWidth: 300,
      autoColorboxJavaScript: false,
      autoHideFlash: false,
      autoColorbox: false,
      autoColorboxGalleries: false,
      colorboxAddClassToLinks: false,
      useGoogleJQuery: false,
      addZoomOverlay: false
    };
  }