function(a,c,n){var l=c.audio&&c.video,r=!1;if(l)a=document.createElement("video"),c.videoBuffered="buffered"in a,r="loop"in a,n.capturingEvents("play,playing,waiting,paused,ended,durationchange,loadedmetadata,canplay,volumechange".split(",")),c.videoBuffered||(n.addPolyfill("mediaelement-native-fix",{f:"mediaelement",test:c.videoBuffered,d:["dom-support"]}),n.reTest("mediaelement-native-fix"));jQuery.webshims.register("mediaelement-core",function(a,c,n,v,t){var q=c.mediaelement,w=c.cfg.mediaelement,
x=function(b,d){var b=a(b),f={src:b.attr("src")||"",elem:b,srcProp:b.prop("src")};if(!f.src)return f;var h=b.attr("type");if(h)f.type=h,f.container=a.trim(h.split(";")[0]);else if(d||(d=b[0].nodeName.toLowerCase(),"source"==d&&(d=(b.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),h=q.getTypeForSrc(f.src,d))f.type=h,f.container=h,c.warn("you should always provide a proper mime-type using the source element. "+f.src+" detected as: "+h),a.nodeName(b[0],"source")&&b.attr("type",
h);if(h=b.attr("media"))f.media=h;return f},b=swfobject.hasFlashPlayerVersion("9.0.115"),o=function(){c.ready("mediaelement-swf",function(){if(!q.createSWF)c.modules["mediaelement-swf"].test=a.noop,c.reTest(["mediaelement-swf"],l)})};q.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],"audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":"mp4,mpg4,m4r,m4a,m4p,m4b,aac".split(","),"audio/wav":["wav"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"],"audio/fla":["flv","f4a","fla"],"application/x-mpegURL":["m3u8",
"m3u"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"],"application/x-mpegURL":["m3u8","m3u"],"video/MP2T":["ts"]}};q.mimeTypes.source=a.extend({},q.mimeTypes.audio,q.mimeTypes.video);q.getTypeForSrc=function(b,c){if(-1!=b.indexOf("youtube.com/watch?")||-1!=b.indexOf("youtube.com/v/"))return"video/youtube";
var b=b.split("?")[0].split("."),b=b[b.length-1],f;a.each(q.mimeTypes[c],function(a,c){if(-1!==c.indexOf(b))return f=a,!1});return f};q.srces=function(b,c){b=a(b);if(c)b.removeAttr("src").removeAttr("type").find("source").remove(),a.isArray(c)||(c=[c]),c.forEach(function(a){var c=v.createElement("source");"string"==typeof a&&(a={src:a});c.setAttribute("src",a.src);a.type&&c.setAttribute("type",a.type);a.media&&c.setAttribute("media",a.media);b.append(c)});else{var c=[],f=b[0].nodeName.toLowerCase(),
h=x(b,f);h.src?c.push(h):a("source",b).each(function(){h=x(this,f);h.src&&c.push(h)});return c}};a.fn.loadMediaSrc=function(b,c){return this.each(function(){c!==t&&(a(this).removeAttr("poster"),c&&a.attr(this,"poster",c));q.srces(this,b);a(this).mediaLoad()})};q.swfMimeTypes="video/3gpp,video/x-msvideo,video/quicktime,video/x-m4v,video/mp4,video/m4p,video/x-flv,video/flv,audio/mpeg,audio/aac,audio/mp4,audio/x-m4a,audio/m4a,audio/mp3,audio/x-fla,audio/fla,youtube/flv,jwplayer/jwplayer,video/youtube".split(",");
q.canSwfPlaySrces=function(c,d){var f="";b&&(c=a(c),d=d||q.srces(c),a.each(d,function(a,b){if(b.container&&b.src&&-1!=q.swfMimeTypes.indexOf(b.container))return f=b,!1}));return f};var p={};q.canNativePlaySrces=function(b,c){var f="";if(l){var b=a(b),h=(b[0].nodeName||"").toLowerCase();if(!p[h])return f;c=c||q.srces(b);a.each(c,function(a,c){if(c.type&&p[h].prop._supvalue.call(b[0],c.type))return f=c,!1})}return f};q.setError=function(b,d){d||(d="can't play sources");a(b).pause().data("mediaerror",
d);c.warn("mediaelementError: "+d);setTimeout(function(){a(b).data("mediaerror")&&a(b).trigger("mediaerror")},1)};var i=function(){var a;return function(b,f,h){c.ready("mediaelement-swf",function(){q.createSWF?q.createSWF(b,f,h):a||(a=!0,o(),i(b,f,h))})}}(),g=function(a,b,c,h,j){c||!1!==c&&b&&"flash"==b.isActive?(c=q.canSwfPlaySrces(a,h))?i(a,c,b):j?q.setError(a,!1):g(a,b,!1,h,!0):(c=q.canNativePlaySrces(a,h))?b&&"flash"==b.isActive&&q.setActive(a,"html5",b):j?(q.setError(a,!1),b&&"flash"==b.isActive&&
q.setActive(a,"html5",b)):g(a,b,!0,h,!0)},m=/^(?:embed|object|datalist)$/i,k=function(b,d){var f=c.data(b,"mediaelementBase")||c.data(b,"mediaelementBase",{}),h=q.srces(b),i=b.parentNode;clearTimeout(f.loadTimer);a.data(b,"mediaerror",!1);if(h.length&&i&&!(1!=i.nodeType||m.test(i.nodeName||"")))d=d||c.data(b,"mediaelement"),g(b,d,w.preferFlash||t,h)};a(v).bind("ended",function(b){var d=c.data(b.target,"mediaelement");(!r||d&&"html5"!=d.isActive||a.prop(b.target,"loop"))&&setTimeout(function(){!a.prop(b.target,
"paused")&&a.prop(b.target,"loop")&&a(b.target).prop("currentTime",0).play()},1)});r||c.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(e){var d=c.defineNodeNameProperty(e,"load",{prop:{value:function(){var a=c.data(this,"mediaelement");k(this,a);l&&(!a||"html5"==a.isActive)&&d.prop._supvalue&&d.prop._supvalue.apply(this,arguments)}}});p[e]=c.defineNodeNameProperty(e,"canPlayType",{prop:{value:function(c){var d="";l&&p[e].prop._supvalue&&(d=p[e].prop._supvalue.call(this,
c),"no"==d&&(d=""));!d&&b&&(c=a.trim((c||"").split(";")[0]),-1!=q.swfMimeTypes.indexOf(c)&&(d="maybe"));return d}}})});c.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,b=c.data(a,"mediaelementBase")||c.data(a,"mediaelementBase",{});clearTimeout(b.loadTimer);b.loadTimer=setTimeout(function(){k(a);a=null},9)}});n=function(){c.addReady(function(b,d){a("video, audio",b).add(d.filter("video, audio")).each(function(){a.browser.msie&&8<c.browserVersion&&a.prop(this,
"paused")&&!a.prop(this,"readyState")&&a(this).is('audio[preload="none"][controls]:not([autoplay])')?a(this).prop("preload","metadata").mediaLoad():k(this);if(l){var b,d,e=this,g=function(){var b=a.prop(e,"buffered");if(b){for(var c="",d=0,f=b.length;d<f;d++)c+=b.end(d);return c}},i=function(){var b=g();b!=d&&(d=b,a(e).triggerHandler("progress"))};a(this).bind("play loadstart progress",function(a){"progress"==a.type&&(d=g());clearTimeout(b);b=setTimeout(i,999)}).bind("emptied stalled mediaerror abort suspend",
function(a){"emptied"==a.type&&(d=!1);clearTimeout(b)})}})})};l?(c.isReady("mediaelement-core",!0),n(),b&&c.ready("WINDOWLOAD mediaelement",o)):c.ready("mediaelement-swf",n)})}