function(b,d,i){var j=d.audio&&d.video,l=!1;if(j)b=document.createElement("video"),d.videoBuffered="buffered"in b,l="loop"in b,i.capturingEvents("play,playing,waiting,paused,ended,durationchange,loadedmetadata,canplay,volumechange".split(",")),d.videoBuffered||(i.addPolyfill("mediaelement-native-fix",{f:"mediaelement",test:d.videoBuffered,d:["dom-support"]}),i.reTest("mediaelement-native-fix"));jQuery.webshims.register("mediaelement-core",function(b,d,i,q,p){var h=d.mediaelement,s=d.cfg.mediaelement,
w=function(a,c){var a=b(a),e={src:a.attr("src")||"",elem:a,srcProp:a.prop("src")};if(!e.src)return e;var f=a.attr("type");if(f)e.type=f,e.container=b.trim(f.split(";")[0]);else if(c||(c=a[0].nodeName.toLowerCase(),"source"==c&&(c=(a.closest("video, audio")[0]||{nodeName:"video"}).nodeName.toLowerCase())),f=h.getTypeForSrc(e.src,c))e.type=f,e.container=f,d.warn("you should always provide a proper mime-type using the source element. "+e.src+" detected as: "+f),b.nodeName(a[0],"source")&&a.attr("type",
f);if(f=a.attr("media"))e.media=f;return e},u=swfobject.hasFlashPlayerVersion("9.0.115"),v=function(){d.ready("mediaelement-swf",function(){if(!h.createSWF)d.modules["mediaelement-swf"].test=b.noop,d.reTest(["mediaelement-swf"],j)})};h.mimeTypes={audio:{"audio/ogg":["ogg","oga","ogm"],"audio/mpeg":["mp2","mp3","mpga","mpega"],"audio/mp4":"mp4,mpg4,m4r,m4a,m4p,m4b,aac".split(","),"audio/wav":["wav"],"audio/3gpp":["3gp","3gpp"],"audio/webm":["webm"],"audio/fla":["flv","f4a","fla"],"application/x-mpegURL":["m3u8",
"m3u"]},video:{"video/ogg":["ogg","ogv","ogm"],"video/mpeg":["mpg","mpeg","mpe"],"video/mp4":["mp4","mpg4","m4v"],"video/quicktime":["mov","qt"],"video/x-msvideo":["avi"],"video/x-ms-asf":["asf","asx"],"video/flv":["flv","f4v"],"video/3gpp":["3gp","3gpp"],"video/webm":["webm"],"application/x-mpegURL":["m3u8","m3u"],"video/MP2T":["ts"]}};h.mimeTypes.source=b.extend({},h.mimeTypes.audio,h.mimeTypes.video);h.getTypeForSrc=function(a,c){if(-1!=a.indexOf("youtube.com/watch?")||-1!=a.indexOf("youtube.com/v/"))return"video/youtube";
var a=a.split("?")[0].split("."),a=a[a.length-1],e;b.each(h.mimeTypes[c],function(c,b){if(-1!==b.indexOf(a))return e=c,!1});return e};h.srces=function(a,c){a=b(a);if(c)a.removeAttr("src").removeAttr("type").find("source").remove(),b.isArray(c)||(c=[c]),c.forEach(function(c){var b=q.createElement("source");"string"==typeof c&&(c={src:c});b.setAttribute("src",c.src);c.type&&b.setAttribute("type",c.type);c.media&&b.setAttribute("media",c.media);a.append(b)});else{var c=[],e=a[0].nodeName.toLowerCase(),
f=w(a,e);f.src?c.push(f):b("source",a).each(function(){f=w(this,e);f.src&&c.push(f)});return c}};b.fn.loadMediaSrc=function(a,c){return this.each(function(){c!==p&&(b(this).removeAttr("poster"),c&&b.attr(this,"poster",c));h.srces(this,a);b(this).mediaLoad()})};h.swfMimeTypes="video/3gpp,video/x-msvideo,video/quicktime,video/x-m4v,video/mp4,video/m4p,video/x-flv,video/flv,audio/mpeg,audio/aac,audio/mp4,audio/x-m4a,audio/m4a,audio/mp3,audio/x-fla,audio/fla,youtube/flv,jwplayer/jwplayer,video/youtube".split(",");
h.canSwfPlaySrces=function(a,c){var e="";u&&(a=b(a),c=c||h.srces(a),b.each(c,function(a,c){if(c.container&&c.src&&-1!=h.swfMimeTypes.indexOf(c.container))return e=c,!1}));return e};var t={};h.canNativePlaySrces=function(a,c){var e="";if(j){var a=b(a),f=(a[0].nodeName||"").toLowerCase();if(!t[f])return e;c=c||h.srces(a);b.each(c,function(c,b){if(b.type&&t[f].prop._supvalue.call(a[0],b.type))return e=b,!1})}return e};h.setError=function(a,c){c||(c="can't play sources");b(a).pause().data("mediaerror",
c);d.warn("mediaelementError: "+c);setTimeout(function(){b(a).data("mediaerror")&&b(a).trigger("mediaerror")},1)};var y=function(){var a;return function(c,b,f){d.ready("mediaelement-swf",function(){h.createSWF?h.createSWF(c,b,f):a||(a=!0,v(),y(c,b,f))})}}(),g=function(a,c,b,f,d){b||!1!==b&&c&&"flash"==c.isActive?(b=h.canSwfPlaySrces(a,f))?y(a,b,c):d?h.setError(a,!1):g(a,c,!1,f,!0):(b=h.canNativePlaySrces(a,f))?c&&"flash"==c.isActive&&h.setActive(a,"html5",c):d?(h.setError(a,!1),c&&"flash"==c.isActive&&
h.setActive(a,"html5",c)):g(a,c,!0,f,!0)},o=/^(?:embed|object|datalist)$/i,x=function(a,c){var e=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{}),f=h.srces(a),n=a.parentNode;clearTimeout(e.loadTimer);b.data(a,"mediaerror",!1);if(f.length&&n&&!(1!=n.nodeType||o.test(n.nodeName||"")))c=c||d.data(a,"mediaelement"),g(a,c,s.preferFlash||p,f)};b(q).bind("ended",function(a){var c=d.data(a.target,"mediaelement");(!l||c&&"html5"!=c.isActive||b.prop(a.target,"loop"))&&setTimeout(function(){!b.prop(a.target,
"paused")&&b.prop(a.target,"loop")&&b(a.target).prop("currentTime",0).play()},1)});l||d.defineNodeNamesBooleanProperty(["audio","video"],"loop");["audio","video"].forEach(function(a){var c=d.defineNodeNameProperty(a,"load",{prop:{value:function(){var a=d.data(this,"mediaelement");x(this,a);j&&(!a||"html5"==a.isActive)&&c.prop._supvalue&&c.prop._supvalue.apply(this,arguments)}}});t[a]=d.defineNodeNameProperty(a,"canPlayType",{prop:{value:function(c){var f="";j&&t[a].prop._supvalue&&(f=t[a].prop._supvalue.call(this,
c),"no"==f&&(f=""));!f&&u&&(c=b.trim((c||"").split(";")[0]),-1!=h.swfMimeTypes.indexOf(c)&&(f="maybe"));return f}}})});d.onNodeNamesPropertyModify(["audio","video"],["src","poster"],{set:function(){var a=this,c=d.data(a,"mediaelementBase")||d.data(a,"mediaelementBase",{});clearTimeout(c.loadTimer);c.loadTimer=setTimeout(function(){x(a);a=null},9)}});i=function(){d.addReady(function(a,c){b("video, audio",a).add(c.filter("video, audio")).each(function(){b.browser.msie&&8<d.browserVersion&&b.prop(this,
"paused")&&!b.prop(this,"readyState")&&b(this).is('audio[preload="none"][controls]:not([autoplay])')?b(this).prop("preload","metadata").mediaLoad():x(this);if(j){var a,c,g=this,o=function(){var a=b.prop(g,"buffered");if(a){for(var c="",e=0,f=a.length;e<f;e++)c+=a.end(e);return c}},h=function(){var a=o();a!=c&&(c=a,b(g).triggerHandler("progress"))};b(this).bind("play loadstart progress",function(b){"progress"==b.type&&(c=o());clearTimeout(a);a=setTimeout(h,999)}).bind("emptied stalled mediaerror abort suspend",
function(b){"emptied"==b.type&&(c=!1);clearTimeout(a)})}})})};j?(d.isReady("mediaelement-core",!0),i(),u&&d.ready("WINDOWLOAD mediaelement",v)):d.ready("mediaelement-swf",i)})}